package cluster

import (
	"context"
	"crypto/md5"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"github.com/google/uuid"

	"github.com/gritive/GrainFS/internal/storage"
)

// ErrStalePlacement signals the placement group changed between the
// coordinator's placement resolve and FSM apply (rebalance window). The
// coordinator (Task 21) performs transparent retry up to 2 times before
// returning 503 SlowDown to the client.
var ErrStalePlacement = errors.New("append: placement group changed mid-request")

// AppendObject implements storage.AppendObjecter for DistributedBackend.
// Owner-node entry point — ClusterCoordinator handles non-owner forwarding
// (Task 21).
//
// Phase A flow:
//  1. Cluster-aware pre-check via HeadObject (fast reject for offset / cap).
//  2. Write segment blob to owner-node disk.
//  3. Propose CmdAppendObject via data-Raft; b.propose surfaces apply errors
//     transparently (Phase A Tasks 14-16).
//  4. Re-HeadObject for fresh result reflecting committed segment list.
func (b *DistributedBackend) AppendObject(ctx context.Context, bucket, key string, expectedOffset int64, r io.Reader) (*storage.Object, error) {
	// Step 1: cluster-aware pre-check.
	existing, err := b.HeadObject(ctx, bucket, key)
	if err != nil && !errors.Is(err, storage.ErrObjectNotFound) {
		return nil, err
	}
	if existing == nil {
		if expectedOffset != 0 {
			return nil, storage.ErrAppendOffsetMismatch
		}
	} else {
		if !existing.IsAppendable {
			return nil, storage.ErrAppendNotSupported
		}
		if existing.Size != expectedOffset {
			return nil, storage.ErrAppendOffsetMismatch
		}
		if len(existing.Segments) >= storage.MaxAppendSegments {
			return nil, storage.ErrAppendCapExceeded
		}
	}

	// Step 2: write segment blob to owner-node disk.
	seg, err := b.writeSegmentBlobForAppend(bucket, key, r)
	if err != nil {
		return nil, fmt.Errorf("write segment blob: %w", err)
	}

	// Step 3: resolve placement group at propose time (cmd captures PG so the
	// FSM can reject if it has moved since — see apply.go ErrStalePlacement).
	pgID := b.lookupPlacementGroupForAppend(ctx, existing)

	// Step 4: propose via data-Raft. b.propose returns FSM apply error
	// transparently (Phase A). VersionID is generated by the propose-time
	// leader (UUIDv7, time-ordered) and frozen into the Raft log so all
	// replicas write the same versioned key; downstream commitObjectIndex
	// reads obj.VersionID from the post-apply HeadObject and proposes the
	// MetaPutObjectIndex entry against meta-Raft.
	versionID := uuid.Must(uuid.NewV7()).String()
	cmd := AppendObjectCmd{
		Bucket:           bucket,
		Key:              key,
		ExpectedOffset:   expectedOffset,
		BlobID:           seg.BlobID,
		SegmentSize:      seg.Size,
		SegmentETag:      seg.ETag,
		PlacementGroupID: pgID,
		VersionID:        versionID,
	}
	if err := b.propose(ctx, CmdAppendObject, cmd); err != nil {
		// Best-effort cleanup of orphan segment blob on apply rejection.
		_ = os.Remove(b.segmentBlobPath(bucket, key, seg.BlobID))
		return nil, err
	}

	// Step 5: re-HeadObject for fresh result.
	obj, herr := b.HeadObject(ctx, bucket, key)
	if herr == nil && obj != nil && obj.IsAppendable {
		b.maybeTriggerCoalesce(bucket, key, obj.Segments)
	}
	return obj, herr
}

// writeSegmentBlobForAppend writes one segment blob to owner-node disk under
// <root>/data/<bucket>/<key>_segments/<blobID>. Mirrors LocalBackend.WriteSegmentBlob
// but uses the cluster backend's own root and (optional) shard-service encryptor.
func (b *DistributedBackend) writeSegmentBlobForAppend(bucket, key string, r io.Reader) (storage.SegmentRef, error) {
	blobID := uuid.Must(uuid.NewV7()).String()
	path := b.segmentBlobPath(bucket, key, blobID)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return storage.SegmentRef{}, err
	}

	h := md5.New()
	f, err := os.Create(path)
	if err != nil {
		return storage.SegmentRef{}, err
	}
	tr := io.TeeReader(r, h)
	size, copyErr := io.Copy(f, tr)
	closeErr := f.Close()
	if copyErr != nil {
		_ = os.Remove(path)
		return storage.SegmentRef{}, copyErr
	}
	if closeErr != nil {
		_ = os.Remove(path)
		return storage.SegmentRef{}, closeErr
	}

	return storage.SegmentRef{
		BlobID: blobID,
		Size:   size,
		ETag:   hex.EncodeToString(h.Sum(nil)),
	}, nil
}

// segmentBlobPath returns the on-disk path for one append-segment blob.
func (b *DistributedBackend) segmentBlobPath(bucket, key, blobID string) string {
	return filepath.Join(b.objectPath(bucket, key)+"_segments", blobID)
}

// openAppendableSegments returns a ReadCloser that stitches all of an
// appendable object's segment blobs into a single byte stream. Each blob is
// opened lazily as Read advances; matches LocalBackend.OpenSegmentedReader's
// behavior for the cluster path. Note: cluster-side segments are written
// unencrypted by writeSegmentBlobForAppend, so this path mirrors that.
//
// Phase B1 (forward-on-read): segment blobs only live on the owner-node's
// disk. When a non-owner serves the GET, local Open returns ENOENT; we
// then fetch the segment from a peer over StreamReadAppendSegment.
// Encryption note: writeSegmentBlobForAppend writes plaintext today; if
// at-rest encryption is later wired into that path, the peer-fetch path
// must reuse the same envelope (see append_segment_transport.go).
func (b *DistributedBackend) openAppendableSegments(bucket, key string, obj *storage.Object) io.ReadCloser {
	total := len(obj.Coalesced) + len(obj.Segments)
	paths := make([]string, 0, total)
	blobIDs := make([]string, 0, total)
	kinds := make([]byte, 0, total)
	// Coalesced blobs come first — they represent the older bytes of the object.
	for _, c := range obj.Coalesced {
		paths = append(paths, b.coalescedBlobPath(bucket, key, c.CoalescedID))
		blobIDs = append(blobIDs, c.CoalescedID)
		kinds = append(kinds, appendSegKindCoalesced)
	}
	for _, s := range obj.Segments {
		paths = append(paths, b.segmentBlobPath(bucket, key, s.BlobID))
		blobIDs = append(blobIDs, s.BlobID)
		kinds = append(kinds, appendSegKindSegment)
	}
	return &appendableSegmentReader{
		backend: b,
		bucket:  bucket,
		key:     key,
		paths:   paths,
		blobIDs: blobIDs,
		kinds:   kinds,
	}
}

type appendableSegmentReader struct {
	backend *DistributedBackend
	bucket  string
	key     string
	paths   []string
	blobIDs []string
	kinds   []byte // appendSegKindSegment | appendSegKindCoalesced per entry
	idx     int
	cur     io.ReadCloser
}

func (r *appendableSegmentReader) Read(p []byte) (int, error) {
	for {
		if r.cur == nil {
			if r.idx >= len(r.paths) {
				return 0, io.EOF
			}
			rc, err := r.openCurrent()
			if err != nil {
				return 0, err
			}
			r.cur = rc
			r.idx++
		}
		n, err := r.cur.Read(p)
		if n > 0 {
			return n, nil
		}
		if errors.Is(err, io.EOF) {
			_ = r.cur.Close()
			r.cur = nil
			continue
		}
		return n, err
	}
}

// openCurrent opens the segment at r.idx. Tries the local file first;
// on ENOENT falls back to a peer fetch (Phase B1 forward-on-read).
//
// Phase B2: the entry may be a coalesced blob — kinds[idx] tells the peer
// fetch which on-disk path to resolve (segment vs coalesced).
func (r *appendableSegmentReader) openCurrent() (io.ReadCloser, error) {
	path := r.paths[r.idx]
	f, err := os.Open(path)
	if err == nil {
		return f, nil
	}
	if !os.IsNotExist(err) {
		return nil, fmt.Errorf("open segment %s: %w", path, err)
	}
	if r.backend == nil {
		return nil, fmt.Errorf("open segment %s: %w", path, err)
	}
	kind := byte(appendSegKindSegment)
	if r.idx < len(r.kinds) {
		kind = r.kinds[r.idx]
	}
	rc, ferr := r.backend.fetchAppendBlobFromAnyPeer(context.Background(), r.bucket, r.key, r.blobIDs[r.idx], kind)
	if ferr != nil {
		return nil, fmt.Errorf("open segment %s (local missing, peer fetch failed): %w", path, ferr)
	}
	return rc, nil
}

func (r *appendableSegmentReader) Close() error {
	if r.cur != nil {
		err := r.cur.Close()
		r.cur = nil
		return err
	}
	return nil
}

// lookupPlacementGroupForAppend resolves the placement group ID to freeze into
// AppendObjectCmd. Order:
//  1. existing objectMeta's PG (anchors subsequent appends to the original PG).
//  2. PlacementGroupFromContext (coordinator-provided).
//  3. default "group-0" (single-node / test path).
func (b *DistributedBackend) lookupPlacementGroupForAppend(ctx context.Context, existing *storage.Object) string {
	// Phase A: storage.Object does not carry PlacementGroupID directly — the FSM
	// reads it from objectMeta at apply time. For the propose-time hint we fall
	// back to context / default; the FSM's stale-placement check still works
	// because applyAppendObjectFromCmd compares cmd.PlacementGroupID against
	// the freshly-read existing objectMeta.PlacementGroupID.
	if existing != nil {
		// existing was decoded from objectMeta; PG isn't exposed on storage.Object,
		// so fall through to context / default. (Task 21 coordinator threads PG
		// via context explicitly.)
		_ = existing
	}
	if pg, ok := PlacementGroupFromContext(ctx); ok {
		return pg
	}
	return "group-0"
}
