// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packblobpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BlobLocation struct {
	_tab flatbuffers.Table
}

func GetRootAsBlobLocation(buf []byte, offset flatbuffers.UOffsetT) *BlobLocation {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BlobLocation{}
	x.Init(buf, n+offset)
	return x
}

func FinishBlobLocationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBlobLocation(buf []byte, offset flatbuffers.UOffsetT) *BlobLocation {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BlobLocation{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBlobLocationBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BlobLocation) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BlobLocation) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BlobLocation) BlobId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BlobLocation) MutateBlobId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *BlobLocation) Offset() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BlobLocation) MutateOffset(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *BlobLocation) Length() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *BlobLocation) MutateLength(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func BlobLocationStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func BlobLocationAddBlobId(builder *flatbuffers.Builder, blobId uint64) {
	builder.PrependUint64Slot(0, blobId, 0)
}
func BlobLocationAddOffset(builder *flatbuffers.Builder, offset uint64) {
	builder.PrependUint64Slot(1, offset, 0)
}
func BlobLocationAddLength(builder *flatbuffers.Builder, length uint32) {
	builder.PrependUint32Slot(2, length, 0)
}
func BlobLocationEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
