// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package packblobpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IndexEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsIndexEntry(buf []byte, offset flatbuffers.UOffsetT) *IndexEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IndexEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishIndexEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIndexEntry(buf []byte, offset flatbuffers.UOffsetT) *IndexEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IndexEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIndexEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *IndexEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IndexEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IndexEntry) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *IndexEntry) Location(obj *BlobLocation) *BlobLocation {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(BlobLocation)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *IndexEntry) Refcount() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *IndexEntry) MutateRefcount(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *IndexEntry) OriginalSize() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *IndexEntry) MutateOriginalSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *IndexEntry) ContentType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *IndexEntry) Etag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *IndexEntry) LastModified() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *IndexEntry) MutateLastModified(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *IndexEntry) UserMetadata(obj *KV, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *IndexEntry) UserMetadataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *IndexEntry) SseAlgorithm() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func IndexEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(9)
}
func IndexEntryAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func IndexEntryAddLocation(builder *flatbuffers.Builder, location flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(location), 0)
}
func IndexEntryAddRefcount(builder *flatbuffers.Builder, refcount int64) {
	builder.PrependInt64Slot(2, refcount, 0)
}
func IndexEntryAddOriginalSize(builder *flatbuffers.Builder, originalSize int64) {
	builder.PrependInt64Slot(3, originalSize, 0)
}
func IndexEntryAddContentType(builder *flatbuffers.Builder, contentType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(contentType), 0)
}
func IndexEntryAddEtag(builder *flatbuffers.Builder, etag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(etag), 0)
}
func IndexEntryAddLastModified(builder *flatbuffers.Builder, lastModified int64) {
	builder.PrependInt64Slot(6, lastModified, 0)
}
func IndexEntryAddUserMetadata(builder *flatbuffers.Builder, userMetadata flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(userMetadata), 0)
}
func IndexEntryStartUserMetadataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func IndexEntryAddSseAlgorithm(builder *flatbuffers.Builder, sseAlgorithm flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(sseAlgorithm), 0)
}
func IndexEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
