run:
  timeout: 5m
  tests: false

linters:
  enable:
    - errcheck
    - govet
    - gosimple
    - ineffassign
    - staticcheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: internal/nfs4server/
      linters:
        - errcheck
      text: "Error return value of `(.*ReadUint.*|.*ReadOpaque|.*ReadFixed|.*ReadString|io.ReadFull)` is not checked"
