// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package receiptpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HealReceipt struct {
	_tab flatbuffers.Table
}

func GetRootAsHealReceipt(buf []byte, offset flatbuffers.UOffsetT) *HealReceipt {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HealReceipt{}
	x.Init(buf, n+offset)
	return x
}

func FinishHealReceiptBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHealReceipt(buf []byte, offset flatbuffers.UOffsetT) *HealReceipt {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HealReceipt{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHealReceiptBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HealReceipt) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HealReceipt) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HealReceipt) ReceiptId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HealReceipt) KeyId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HealReceipt) TimestampUnixNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HealReceipt) MutateTimestampUnixNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *HealReceipt) Object(obj *ObjectRef) *ObjectRef {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ObjectRef)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *HealReceipt) ShardsLost(j int) int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *HealReceipt) ShardsLostLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *HealReceipt) MutateShardsLost(j int, n int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *HealReceipt) ShardsRebuilt(j int) int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetInt32(a + flatbuffers.UOffsetT(j*4))
	}
	return 0
}

func (rcv *HealReceipt) ShardsRebuiltLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *HealReceipt) MutateShardsRebuilt(j int, n int32) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateInt32(a+flatbuffers.UOffsetT(j*4), n)
	}
	return false
}

func (rcv *HealReceipt) ParityUsed() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HealReceipt) MutateParityUsed(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *HealReceipt) PeersInvolved(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *HealReceipt) PeersInvolvedLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *HealReceipt) DurationMs() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *HealReceipt) MutateDurationMs(n uint32) bool {
	return rcv._tab.MutateUint32Slot(20, n)
}

func (rcv *HealReceipt) EventIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *HealReceipt) EventIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *HealReceipt) CorrelationId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HealReceipt) CanonicalPayload() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HealReceipt) Signature() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func HealReceiptStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func HealReceiptAddReceiptId(builder *flatbuffers.Builder, receiptId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(receiptId), 0)
}
func HealReceiptAddKeyId(builder *flatbuffers.Builder, keyId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(keyId), 0)
}
func HealReceiptAddTimestampUnixNs(builder *flatbuffers.Builder, timestampUnixNs int64) {
	builder.PrependInt64Slot(2, timestampUnixNs, 0)
}
func HealReceiptAddObject(builder *flatbuffers.Builder, object flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(object), 0)
}
func HealReceiptAddShardsLost(builder *flatbuffers.Builder, shardsLost flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(shardsLost), 0)
}
func HealReceiptStartShardsLostVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func HealReceiptAddShardsRebuilt(builder *flatbuffers.Builder, shardsRebuilt flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(shardsRebuilt), 0)
}
func HealReceiptStartShardsRebuiltVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func HealReceiptAddParityUsed(builder *flatbuffers.Builder, parityUsed int32) {
	builder.PrependInt32Slot(6, parityUsed, 0)
}
func HealReceiptAddPeersInvolved(builder *flatbuffers.Builder, peersInvolved flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(peersInvolved), 0)
}
func HealReceiptStartPeersInvolvedVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func HealReceiptAddDurationMs(builder *flatbuffers.Builder, durationMs uint32) {
	builder.PrependUint32Slot(8, durationMs, 0)
}
func HealReceiptAddEventIds(builder *flatbuffers.Builder, eventIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(eventIds), 0)
}
func HealReceiptStartEventIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func HealReceiptAddCorrelationId(builder *flatbuffers.Builder, correlationId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(correlationId), 0)
}
func HealReceiptAddCanonicalPayload(builder *flatbuffers.Builder, canonicalPayload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(canonicalPayload), 0)
}
func HealReceiptAddSignature(builder *flatbuffers.Builder, signature flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(signature), 0)
}
func HealReceiptEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
