package server

const (
	routePathS3Root   = "/"
	routePathS3Bucket = "/:bucket"
	routePathS3Object = "/:bucket/*key"

	routePathMetrics = "/metrics"
	routePathUI      = "/ui"
	routePathUIRoot  = "/ui/"

	routePrefixAPI     = "/api/"
	routePrefixAdmin   = "/admin/"
	routePrefixIceberg = "/iceberg/"
	routePrefixUI      = "/ui/"

	routePathEvents            = "/api/events"
	routePathHealEventsStream  = "/api/events/heal/stream"
	routePathEventLog          = "/api/eventlog"
	routePathIncidents         = "/api/incidents"
	routePrefixIncidents       = "/api/incidents/"
	routePathClusterStatus     = "/api/cluster/status"
	routePathClusterPlacement  = "/api/cluster/placement"
	routePathClusterJoin       = "/api/cluster/join"
	routePathClusterRemovePeer = "/api/cluster/remove-peer"
	routePathClusterBalancer   = "/api/cluster/balancer/status"
	routePathLifecycleStatus   = "/api/cluster/lifecycle/status"
	routePathAuditHealth       = "/api/audit/health"
	routePathAuditS3           = "/api/audit/s3"
	routePathCacheStatus       = "/api/cache/status"
	routePathConfig            = "/api/admin/config"
	routePathAlertsStatus      = "/api/admin/alerts/status"
	routePathAlertsResend      = "/api/admin/alerts/resend"
	routePathReceipts          = "/api/receipts"
	routePathReceiptByID       = "/api/receipts/:id"

	routePathAdminHealthBadger = "/admin/health/badger"
	routePathAdminHealthRaft   = "/admin/health/raft"
	routePathAdminHealthScrub  = "/admin/health/scrub"
	routePathAdminRaftSnapshot = "/admin/raft/snapshot"
	routePathAdminSnapshots    = "/admin/snapshots"
	routePathAdminPITR         = "/admin/pitr"
	routePathAdminDebug        = "/admin/debug"
	routePathAdminDebugVFSStat = "/vfs/stat"

	routePathSnapshotSeq        = "/:seq"
	routePathSnapshotSeqRestore = "/:seq/restore"

	routePrefixAdminUDSCluster      = "/v1/cluster"
	routePathAdminUDSClusterStatus  = "/status"
	routePathAdminUDSPlacement      = "/placement"
	routePathAdminUDSRemovePeer     = "/remove-peer"
	routePathAdminUDSEventLog       = "/eventlog"
	routePathAdminUDSTransferLeader = "/transfer-leader"
	routePathAdminUDSHealth         = "/health"
	routePathAdminUDSBalancerStatus = "/balancer/status"

	routePathIcebergConfig            = "/iceberg/v1/config"
	routePathIcebergNamespaces        = "/iceberg/v1/namespaces"
	routePathIcebergNamespace         = "/iceberg/v1/namespaces/:namespace"
	routePathIcebergNamespaceTables   = "/iceberg/v1/namespaces/:namespace/tables"
	routePathIcebergTable             = "/iceberg/v1/namespaces/:namespace/tables/:table"
	routePathIcebergTransactionCommit = "/iceberg/v1/transactions/commit"
	routePathIcebergUnsupported       = "/iceberg/*path"
)
