// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package erasurepb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ECObjectMeta struct {
	_tab flatbuffers.Table
}

func GetRootAsECObjectMeta(buf []byte, offset flatbuffers.UOffsetT) *ECObjectMeta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ECObjectMeta{}
	x.Init(buf, n+offset)
	return x
}

func FinishECObjectMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsECObjectMeta(buf []byte, offset flatbuffers.UOffsetT) *ECObjectMeta {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ECObjectMeta{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedECObjectMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ECObjectMeta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ECObjectMeta) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ECObjectMeta) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ECObjectMeta) Size() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ECObjectMeta) MutateSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *ECObjectMeta) ContentType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ECObjectMeta) Etag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ECObjectMeta) LastModified() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ECObjectMeta) MutateLastModified(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *ECObjectMeta) DataShards() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ECObjectMeta) MutateDataShards(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *ECObjectMeta) ParityShards() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ECObjectMeta) MutateParityShards(n int32) bool {
	return rcv._tab.MutateInt32Slot(16, n)
}

func (rcv *ECObjectMeta) ShardSize() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ECObjectMeta) MutateShardSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func (rcv *ECObjectMeta) VersionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ECObjectMeta) IsDeleteMarker() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ECObjectMeta) MutateIsDeleteMarker(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *ECObjectMeta) CreatedNano() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ECObjectMeta) MutateCreatedNano(n int64) bool {
	return rcv._tab.MutateInt64Slot(24, n)
}

func (rcv *ECObjectMeta) Acl() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ECObjectMeta) MutateAcl(n uint32) bool {
	return rcv._tab.MutateUint32Slot(26, n)
}

func ECObjectMetaStart(builder *flatbuffers.Builder) {
	builder.StartObject(12)
}
func ECObjectMetaAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func ECObjectMetaAddSize(builder *flatbuffers.Builder, size int64) {
	builder.PrependInt64Slot(1, size, 0)
}
func ECObjectMetaAddContentType(builder *flatbuffers.Builder, contentType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(contentType), 0)
}
func ECObjectMetaAddEtag(builder *flatbuffers.Builder, etag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(etag), 0)
}
func ECObjectMetaAddLastModified(builder *flatbuffers.Builder, lastModified int64) {
	builder.PrependInt64Slot(4, lastModified, 0)
}
func ECObjectMetaAddDataShards(builder *flatbuffers.Builder, dataShards int32) {
	builder.PrependInt32Slot(5, dataShards, 0)
}
func ECObjectMetaAddParityShards(builder *flatbuffers.Builder, parityShards int32) {
	builder.PrependInt32Slot(6, parityShards, 0)
}
func ECObjectMetaAddShardSize(builder *flatbuffers.Builder, shardSize int32) {
	builder.PrependInt32Slot(7, shardSize, 0)
}
func ECObjectMetaAddVersionId(builder *flatbuffers.Builder, versionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(versionId), 0)
}
func ECObjectMetaAddIsDeleteMarker(builder *flatbuffers.Builder, isDeleteMarker bool) {
	builder.PrependBoolSlot(9, isDeleteMarker, false)
}
func ECObjectMetaAddCreatedNano(builder *flatbuffers.Builder, createdNano int64) {
	builder.PrependInt64Slot(10, createdNano, 0)
}
func ECObjectMetaAddAcl(builder *flatbuffers.Builder, acl uint32) {
	builder.PrependUint32Slot(11, acl, 0)
}
func ECObjectMetaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
