// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/erasure/erasurepb/erasure.proto

package erasurepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BucketMeta struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EcEnabled       bool                   `protobuf:"varint,1,opt,name=ec_enabled,json=ecEnabled,proto3" json:"ec_enabled,omitempty"`
	VersioningState string                 `protobuf:"bytes,2,opt,name=versioning_state,json=versioningState,proto3" json:"versioning_state,omitempty"` // "Unversioned", "Enabled", "Suspended"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BucketMeta) Reset() {
	*x = BucketMeta{}
	mi := &file_internal_erasure_erasurepb_erasure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketMeta) ProtoMessage() {}

func (x *BucketMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_erasure_erasurepb_erasure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketMeta.ProtoReflect.Descriptor instead.
func (*BucketMeta) Descriptor() ([]byte, []int) {
	return file_internal_erasure_erasurepb_erasure_proto_rawDescGZIP(), []int{0}
}

func (x *BucketMeta) GetEcEnabled() bool {
	if x != nil {
		return x.EcEnabled
	}
	return false
}

func (x *BucketMeta) GetVersioningState() string {
	if x != nil {
		return x.VersioningState
	}
	return ""
}

type ECObjectMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Size           int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ContentType    string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Etag           string                 `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModified   int64                  `protobuf:"varint,5,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	DataShards     int32                  `protobuf:"varint,6,opt,name=data_shards,json=dataShards,proto3" json:"data_shards,omitempty"`
	ParityShards   int32                  `protobuf:"varint,7,opt,name=parity_shards,json=parityShards,proto3" json:"parity_shards,omitempty"`
	ShardSize      int32                  `protobuf:"varint,8,opt,name=shard_size,json=shardSize,proto3" json:"shard_size,omitempty"`
	VersionId      string                 `protobuf:"bytes,9,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	IsDeleteMarker bool                   `protobuf:"varint,10,opt,name=is_delete_marker,json=isDeleteMarker,proto3" json:"is_delete_marker,omitempty"`
	CreatedNano    int64                  `protobuf:"varint,11,opt,name=created_nano,json=createdNano,proto3" json:"created_nano,omitempty"` // UnixNano creation time for sub-second version ordering
	Acl            uint32                 `protobuf:"varint,12,opt,name=acl,proto3" json:"acl,omitempty"`                                    // ACLGrant bitmask; 0 = private (backward compat)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ECObjectMeta) Reset() {
	*x = ECObjectMeta{}
	mi := &file_internal_erasure_erasurepb_erasure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECObjectMeta) ProtoMessage() {}

func (x *ECObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_erasure_erasurepb_erasure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECObjectMeta.ProtoReflect.Descriptor instead.
func (*ECObjectMeta) Descriptor() ([]byte, []int) {
	return file_internal_erasure_erasurepb_erasure_proto_rawDescGZIP(), []int{1}
}

func (x *ECObjectMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ECObjectMeta) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ECObjectMeta) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ECObjectMeta) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ECObjectMeta) GetLastModified() int64 {
	if x != nil {
		return x.LastModified
	}
	return 0
}

func (x *ECObjectMeta) GetDataShards() int32 {
	if x != nil {
		return x.DataShards
	}
	return 0
}

func (x *ECObjectMeta) GetParityShards() int32 {
	if x != nil {
		return x.ParityShards
	}
	return 0
}

func (x *ECObjectMeta) GetShardSize() int32 {
	if x != nil {
		return x.ShardSize
	}
	return 0
}

func (x *ECObjectMeta) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ECObjectMeta) GetIsDeleteMarker() bool {
	if x != nil {
		return x.IsDeleteMarker
	}
	return false
}

func (x *ECObjectMeta) GetCreatedNano() int64 {
	if x != nil {
		return x.CreatedNano
	}
	return 0
}

func (x *ECObjectMeta) GetAcl() uint32 {
	if x != nil {
		return x.Acl
	}
	return 0
}

type MultipartUploadMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadId      string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipartUploadMeta) Reset() {
	*x = MultipartUploadMeta{}
	mi := &file_internal_erasure_erasurepb_erasure_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipartUploadMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipartUploadMeta) ProtoMessage() {}

func (x *MultipartUploadMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_erasure_erasurepb_erasure_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipartUploadMeta.ProtoReflect.Descriptor instead.
func (*MultipartUploadMeta) Descriptor() ([]byte, []int) {
	return file_internal_erasure_erasurepb_erasure_proto_rawDescGZIP(), []int{2}
}

func (x *MultipartUploadMeta) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *MultipartUploadMeta) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *MultipartUploadMeta) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MultipartUploadMeta) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MultipartUploadMeta) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_internal_erasure_erasurepb_erasure_proto protoreflect.FileDescriptor

const file_internal_erasure_erasurepb_erasure_proto_rawDesc = "" +
	"\n" +
	"(internal/erasure/erasurepb/erasure.proto\x12\terasurepb\"V\n" +
	"\n" +
	"BucketMeta\x12\x1d\n" +
	"\n" +
	"ec_enabled\x18\x01 \x01(\bR\tecEnabled\x12)\n" +
	"\x10versioning_state\x18\x02 \x01(\tR\x0fversioningState\"\xf3\x02\n" +
	"\fECObjectMeta\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04etag\x18\x04 \x01(\tR\x04etag\x12#\n" +
	"\rlast_modified\x18\x05 \x01(\x03R\flastModified\x12\x1f\n" +
	"\vdata_shards\x18\x06 \x01(\x05R\n" +
	"dataShards\x12#\n" +
	"\rparity_shards\x18\a \x01(\x05R\fparityShards\x12\x1d\n" +
	"\n" +
	"shard_size\x18\b \x01(\x05R\tshardSize\x12\x1d\n" +
	"\n" +
	"version_id\x18\t \x01(\tR\tversionId\x12(\n" +
	"\x10is_delete_marker\x18\n" +
	" \x01(\bR\x0eisDeleteMarker\x12!\n" +
	"\fcreated_nano\x18\v \x01(\x03R\vcreatedNano\x12\x10\n" +
	"\x03acl\x18\f \x01(\rR\x03acl\"\x9e\x01\n" +
	"\x13MultipartUploadMeta\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAtB7Z5github.com/gritive/GrainFS/internal/erasure/erasurepbb\x06proto3"

var (
	file_internal_erasure_erasurepb_erasure_proto_rawDescOnce sync.Once
	file_internal_erasure_erasurepb_erasure_proto_rawDescData []byte
)

func file_internal_erasure_erasurepb_erasure_proto_rawDescGZIP() []byte {
	file_internal_erasure_erasurepb_erasure_proto_rawDescOnce.Do(func() {
		file_internal_erasure_erasurepb_erasure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_erasure_erasurepb_erasure_proto_rawDesc), len(file_internal_erasure_erasurepb_erasure_proto_rawDesc)))
	})
	return file_internal_erasure_erasurepb_erasure_proto_rawDescData
}

var file_internal_erasure_erasurepb_erasure_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_erasure_erasurepb_erasure_proto_goTypes = []any{
	(*BucketMeta)(nil),          // 0: erasurepb.BucketMeta
	(*ECObjectMeta)(nil),        // 1: erasurepb.ECObjectMeta
	(*MultipartUploadMeta)(nil), // 2: erasurepb.MultipartUploadMeta
}
var file_internal_erasure_erasurepb_erasure_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_erasure_erasurepb_erasure_proto_init() }
func file_internal_erasure_erasurepb_erasure_proto_init() {
	if File_internal_erasure_erasurepb_erasure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_erasure_erasurepb_erasure_proto_rawDesc), len(file_internal_erasure_erasurepb_erasure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_erasure_erasurepb_erasure_proto_goTypes,
		DependencyIndexes: file_internal_erasure_erasurepb_erasure_proto_depIdxs,
		MessageInfos:      file_internal_erasure_erasurepb_erasure_proto_msgTypes,
	}.Build()
	File_internal_erasure_erasurepb_erasure_proto = out.File
	file_internal_erasure_erasurepb_erasure_proto_goTypes = nil
	file_internal_erasure_erasurepb_erasure_proto_depIdxs = nil
}
