// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package erasurepb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MultipartUploadMetaFB struct {
	_tab flatbuffers.Table
}

func GetRootAsMultipartUploadMetaFB(buf []byte, offset flatbuffers.UOffsetT) *MultipartUploadMetaFB {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MultipartUploadMetaFB{}
	x.Init(buf, n+offset)
	return x
}

func FinishMultipartUploadMetaFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMultipartUploadMetaFB(buf []byte, offset flatbuffers.UOffsetT) *MultipartUploadMetaFB {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MultipartUploadMetaFB{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMultipartUploadMetaFBBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MultipartUploadMetaFB) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MultipartUploadMetaFB) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MultipartUploadMetaFB) UploadId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MultipartUploadMetaFB) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MultipartUploadMetaFB) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MultipartUploadMetaFB) ContentType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MultipartUploadMetaFB) CreatedAt() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MultipartUploadMetaFB) MutateCreatedAt(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func MultipartUploadMetaFBStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MultipartUploadMetaFBAddUploadId(builder *flatbuffers.Builder, uploadId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(uploadId), 0)
}
func MultipartUploadMetaFBAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(bucket), 0)
}
func MultipartUploadMetaFBAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(key), 0)
}
func MultipartUploadMetaFBAddContentType(builder *flatbuffers.Builder, contentType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(contentType), 0)
}
func MultipartUploadMetaFBAddCreatedAt(builder *flatbuffers.Builder, createdAt int64) {
	builder.PrependInt64Slot(4, createdAt, 0)
}
func MultipartUploadMetaFBEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
