// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package erasurepb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MultipartUploadMeta struct {
	_tab flatbuffers.Table
}

func GetRootAsMultipartUploadMeta(buf []byte, offset flatbuffers.UOffsetT) *MultipartUploadMeta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MultipartUploadMeta{}
	x.Init(buf, n+offset)
	return x
}

func FinishMultipartUploadMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMultipartUploadMeta(buf []byte, offset flatbuffers.UOffsetT) *MultipartUploadMeta {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MultipartUploadMeta{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMultipartUploadMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MultipartUploadMeta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MultipartUploadMeta) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MultipartUploadMeta) UploadId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MultipartUploadMeta) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MultipartUploadMeta) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MultipartUploadMeta) ContentType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MultipartUploadMeta) CreatedAt() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MultipartUploadMeta) MutateCreatedAt(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func MultipartUploadMetaStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MultipartUploadMetaAddUploadId(builder *flatbuffers.Builder, uploadId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(uploadId), 0)
}
func MultipartUploadMetaAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(bucket), 0)
}
func MultipartUploadMetaAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(key), 0)
}
func MultipartUploadMetaAddContentType(builder *flatbuffers.Builder, contentType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(contentType), 0)
}
func MultipartUploadMetaAddCreatedAt(builder *flatbuffers.Builder, createdAt int64) {
	builder.PrependInt64Slot(4, createdAt, 0)
}
func MultipartUploadMetaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
