// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package volumepb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Volume struct {
	_tab flatbuffers.Table
}

func GetRootAsVolume(buf []byte, offset flatbuffers.UOffsetT) *Volume {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Volume{}
	x.Init(buf, n+offset)
	return x
}

func FinishVolumeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsVolume(buf []byte, offset flatbuffers.UOffsetT) *Volume {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Volume{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedVolumeBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Volume) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Volume) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Volume) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Volume) Size() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Volume) MutateSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *Volume) BlockSize() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Volume) MutateBlockSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func (rcv *Volume) AllocatedBlocks() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return -1
}

func (rcv *Volume) MutateAllocatedBlocks(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *Volume) SnapshotCount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Volume) MutateSnapshotCount(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func VolumeStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func VolumeAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func VolumeAddSize(builder *flatbuffers.Builder, size int64) {
	builder.PrependInt64Slot(1, size, 0)
}
func VolumeAddBlockSize(builder *flatbuffers.Builder, blockSize int32) {
	builder.PrependInt32Slot(2, blockSize, 0)
}
func VolumeAddAllocatedBlocks(builder *flatbuffers.Builder, allocatedBlocks int64) {
	builder.PrependInt64Slot(3, allocatedBlocks, -1)
}
func VolumeAddSnapshotCount(builder *flatbuffers.Builder, snapshotCount int32) {
	builder.PrependInt32Slot(4, snapshotCount, 0)
}
func VolumeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
