// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import "strconv"

type AbortPlanReason byte

const (
	AbortPlanReasonUnknown         AbortPlanReason = 0
	AbortPlanReasonTimeout         AbortPlanReason = 1
	AbortPlanReasonExecutionFailed AbortPlanReason = 2
	AbortPlanReasonCompleted       AbortPlanReason = 3
)

var EnumNamesAbortPlanReason = map[AbortPlanReason]string{
	AbortPlanReasonUnknown:         "Unknown",
	AbortPlanReasonTimeout:         "Timeout",
	AbortPlanReasonExecutionFailed: "ExecutionFailed",
	AbortPlanReasonCompleted:       "Completed",
}

var EnumValuesAbortPlanReason = map[string]AbortPlanReason{
	"Unknown":         AbortPlanReasonUnknown,
	"Timeout":         AbortPlanReasonTimeout,
	"ExecutionFailed": AbortPlanReasonExecutionFailed,
	"Completed":       AbortPlanReasonCompleted,
}

func (v AbortPlanReason) String() string {
	if s, ok := EnumNamesAbortPlanReason[v]; ok {
		return s
	}
	return "AbortPlanReason(" + strconv.FormatInt(int64(v), 10) + ")"
}
