// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BoolBox struct {
	_tab flatbuffers.Table
}

func GetRootAsBoolBox(buf []byte, offset flatbuffers.UOffsetT) *BoolBox {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BoolBox{}
	x.Init(buf, n+offset)
	return x
}

func FinishBoolBoxBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBoolBox(buf []byte, offset flatbuffers.UOffsetT) *BoolBox {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BoolBox{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBoolBoxBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BoolBox) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BoolBox) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BoolBox) V() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BoolBox) MutateV(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func BoolBoxStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BoolBoxAddV(builder *flatbuffers.Builder, v bool) {
	builder.PrependBoolSlot(0, v, false)
}
func BoolBoxEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
