// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BootstrapSecretsPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsBootstrapSecretsPayload(buf []byte, offset flatbuffers.UOffsetT) *BootstrapSecretsPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BootstrapSecretsPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishBootstrapSecretsPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBootstrapSecretsPayload(buf []byte, offset flatbuffers.UOffsetT) *BootstrapSecretsPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BootstrapSecretsPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBootstrapSecretsPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BootstrapSecretsPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BootstrapSecretsPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BootstrapSecretsPayload) EncryptionKey(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BootstrapSecretsPayload) EncryptionKeyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BootstrapSecretsPayload) EncryptionKeyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BootstrapSecretsPayload) MutateEncryptionKey(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BootstrapSecretsPayload) KekGenerations(obj *KEKGen, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BootstrapSecretsPayload) KekGenerationsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BootstrapSecretsPayload) TransportPsk(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *BootstrapSecretsPayload) TransportPskLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BootstrapSecretsPayload) TransportPskBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BootstrapSecretsPayload) MutateTransportPsk(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *BootstrapSecretsPayload) PeerSpkis(obj *SPKIBytes, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *BootstrapSecretsPayload) PeerSpkisLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *BootstrapSecretsPayload) ClusterKeyDropped() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *BootstrapSecretsPayload) MutateClusterKeyDropped(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func BootstrapSecretsPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func BootstrapSecretsPayloadAddEncryptionKey(builder *flatbuffers.Builder, encryptionKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(encryptionKey), 0)
}
func BootstrapSecretsPayloadStartEncryptionKeyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BootstrapSecretsPayloadAddKekGenerations(builder *flatbuffers.Builder, kekGenerations flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(kekGenerations), 0)
}
func BootstrapSecretsPayloadStartKekGenerationsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BootstrapSecretsPayloadAddTransportPsk(builder *flatbuffers.Builder, transportPsk flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(transportPsk), 0)
}
func BootstrapSecretsPayloadStartTransportPskVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func BootstrapSecretsPayloadAddPeerSpkis(builder *flatbuffers.Builder, peerSpkis flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(peerSpkis), 0)
}
func BootstrapSecretsPayloadStartPeerSpkisVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func BootstrapSecretsPayloadAddClusterKeyDropped(builder *flatbuffers.Builder, clusterKeyDropped bool) {
	builder.PrependBoolSlot(4, clusterKeyDropped, false)
}
func BootstrapSecretsPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
