// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import "strconv"

type CatalogReadOp int8

const (
	CatalogReadOpUnknown        CatalogReadOp = 0
	CatalogReadOpLoadNamespace  CatalogReadOp = 1
	CatalogReadOpListNamespaces CatalogReadOp = 2
	CatalogReadOpLoadTable      CatalogReadOp = 3
	CatalogReadOpListTables     CatalogReadOp = 4
)

var EnumNamesCatalogReadOp = map[CatalogReadOp]string{
	CatalogReadOpUnknown:        "Unknown",
	CatalogReadOpLoadNamespace:  "LoadNamespace",
	CatalogReadOpListNamespaces: "ListNamespaces",
	CatalogReadOpLoadTable:      "LoadTable",
	CatalogReadOpListTables:     "ListTables",
}

var EnumValuesCatalogReadOp = map[string]CatalogReadOp{
	"Unknown":        CatalogReadOpUnknown,
	"LoadNamespace":  CatalogReadOpLoadNamespace,
	"ListNamespaces": CatalogReadOpListNamespaces,
	"LoadTable":      CatalogReadOpLoadTable,
	"ListTables":     CatalogReadOpListTables,
}

func (v CatalogReadOp) String() string {
	if s, ok := EnumNamesCatalogReadOp[v]; ok {
		return s
	}
	return "CatalogReadOp(" + strconv.FormatInt(int64(v), 10) + ")"
}
