// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CatalogIdentifier struct {
	_tab flatbuffers.Table
}

func GetRootAsCatalogIdentifier(buf []byte, offset flatbuffers.UOffsetT) *CatalogIdentifier {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CatalogIdentifier{}
	x.Init(buf, n+offset)
	return x
}

func FinishCatalogIdentifierBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCatalogIdentifier(buf []byte, offset flatbuffers.UOffsetT) *CatalogIdentifier {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CatalogIdentifier{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCatalogIdentifierBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CatalogIdentifier) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CatalogIdentifier) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CatalogIdentifier) Namespace(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *CatalogIdentifier) NamespaceLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CatalogIdentifier) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CatalogIdentifierStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CatalogIdentifierAddNamespace(builder *flatbuffers.Builder, namespace flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(namespace), 0)
}
func CatalogIdentifierStartNamespaceVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CatalogIdentifierAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func CatalogIdentifierEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
