// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClusterConfig struct {
	_tab flatbuffers.Table
}

func GetRootAsClusterConfig(buf []byte, offset flatbuffers.UOffsetT) *ClusterConfig {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClusterConfig{}
	x.Init(buf, n+offset)
	return x
}

func FinishClusterConfigBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClusterConfig(buf []byte, offset flatbuffers.UOffsetT) *ClusterConfig {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClusterConfig{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClusterConfigBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClusterConfig) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClusterConfig) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClusterConfig) Rev() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClusterConfig) MutateRev(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *ClusterConfig) UpdatedAtUnixMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClusterConfig) MutateUpdatedAtUnixMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *ClusterConfig) BalancerEnabled(obj *BoolBox) *BoolBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(BoolBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BalancerImbalanceTriggerPct(obj *DoubleBox) *DoubleBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DoubleBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BalancerImbalanceStopPct(obj *DoubleBox) *DoubleBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DoubleBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BalancerMigrationRate(obj *Int32Box) *Int32Box {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Int32Box)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BalancerLeaderTenureMinNs(obj *Int64Box) *Int64Box {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Int64Box)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BalancerWarmupTimeoutNs(obj *Int64Box) *Int64Box {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Int64Box)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BalancerCbThreshold(obj *DoubleBox) *DoubleBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DoubleBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BalancerMigrationMaxRetries(obj *Int32Box) *Int32Box {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Int32Box)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BalancerMigrationPendingTtlNs(obj *Int64Box) *Int64Box {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Int64Box)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BalancerGossipIntervalNs(obj *Int64Box) *Int64Box {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Int64Box)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) AlertWebhook() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClusterConfig) AlertWebhookSecretWrapped(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ClusterConfig) AlertWebhookSecretWrappedLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ClusterConfig) AlertWebhookSecretWrappedBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClusterConfig) MutateAlertWebhookSecretWrapped(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ClusterConfig) DiskWarnFrac(obj *DoubleBox) *DoubleBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DoubleBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) DiskCriticalFrac(obj *DoubleBox) *DoubleBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(34))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DoubleBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) SnapshotIntervalNs(obj *Int64Box) *Int64Box {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(36))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Int64Box)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) SnapshotRetain(obj *Int32Box) *Int32Box {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(38))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Int32Box)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) WeightedHrwEnabled(obj *BoolBox) *BoolBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(40))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(BoolBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BoundedLoadsEnabled(obj *BoolBox) *BoolBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(42))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(BoolBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BoundedLoadsC(obj *DoubleBox) *DoubleBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(44))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DoubleBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BoundedLoadsCLow(obj *DoubleBox) *DoubleBox {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(46))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(DoubleBox)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ClusterConfig) BoundedLoadsMaxStaleTtlNs(obj *Int64Box) *Int64Box {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(48))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Int64Box)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ClusterConfigStart(builder *flatbuffers.Builder) {
	builder.StartObject(23)
}
func ClusterConfigAddRev(builder *flatbuffers.Builder, rev uint64) {
	builder.PrependUint64Slot(0, rev, 0)
}
func ClusterConfigAddUpdatedAtUnixMs(builder *flatbuffers.Builder, updatedAtUnixMs int64) {
	builder.PrependInt64Slot(1, updatedAtUnixMs, 0)
}
func ClusterConfigAddBalancerEnabled(builder *flatbuffers.Builder, balancerEnabled flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(balancerEnabled), 0)
}
func ClusterConfigAddBalancerImbalanceTriggerPct(builder *flatbuffers.Builder, balancerImbalanceTriggerPct flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(balancerImbalanceTriggerPct), 0)
}
func ClusterConfigAddBalancerImbalanceStopPct(builder *flatbuffers.Builder, balancerImbalanceStopPct flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(balancerImbalanceStopPct), 0)
}
func ClusterConfigAddBalancerMigrationRate(builder *flatbuffers.Builder, balancerMigrationRate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(balancerMigrationRate), 0)
}
func ClusterConfigAddBalancerLeaderTenureMinNs(builder *flatbuffers.Builder, balancerLeaderTenureMinNs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(balancerLeaderTenureMinNs), 0)
}
func ClusterConfigAddBalancerWarmupTimeoutNs(builder *flatbuffers.Builder, balancerWarmupTimeoutNs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(balancerWarmupTimeoutNs), 0)
}
func ClusterConfigAddBalancerCbThreshold(builder *flatbuffers.Builder, balancerCbThreshold flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(balancerCbThreshold), 0)
}
func ClusterConfigAddBalancerMigrationMaxRetries(builder *flatbuffers.Builder, balancerMigrationMaxRetries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(balancerMigrationMaxRetries), 0)
}
func ClusterConfigAddBalancerMigrationPendingTtlNs(builder *flatbuffers.Builder, balancerMigrationPendingTtlNs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(balancerMigrationPendingTtlNs), 0)
}
func ClusterConfigAddBalancerGossipIntervalNs(builder *flatbuffers.Builder, balancerGossipIntervalNs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(balancerGossipIntervalNs), 0)
}
func ClusterConfigAddAlertWebhook(builder *flatbuffers.Builder, alertWebhook flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(12, flatbuffers.UOffsetT(alertWebhook), 0)
}
func ClusterConfigAddAlertWebhookSecretWrapped(builder *flatbuffers.Builder, alertWebhookSecretWrapped flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(13, flatbuffers.UOffsetT(alertWebhookSecretWrapped), 0)
}
func ClusterConfigStartAlertWebhookSecretWrappedVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ClusterConfigAddDiskWarnFrac(builder *flatbuffers.Builder, diskWarnFrac flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(diskWarnFrac), 0)
}
func ClusterConfigAddDiskCriticalFrac(builder *flatbuffers.Builder, diskCriticalFrac flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(15, flatbuffers.UOffsetT(diskCriticalFrac), 0)
}
func ClusterConfigAddSnapshotIntervalNs(builder *flatbuffers.Builder, snapshotIntervalNs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(16, flatbuffers.UOffsetT(snapshotIntervalNs), 0)
}
func ClusterConfigAddSnapshotRetain(builder *flatbuffers.Builder, snapshotRetain flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(17, flatbuffers.UOffsetT(snapshotRetain), 0)
}
func ClusterConfigAddWeightedHrwEnabled(builder *flatbuffers.Builder, weightedHrwEnabled flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(18, flatbuffers.UOffsetT(weightedHrwEnabled), 0)
}
func ClusterConfigAddBoundedLoadsEnabled(builder *flatbuffers.Builder, boundedLoadsEnabled flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(19, flatbuffers.UOffsetT(boundedLoadsEnabled), 0)
}
func ClusterConfigAddBoundedLoadsC(builder *flatbuffers.Builder, boundedLoadsC flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(20, flatbuffers.UOffsetT(boundedLoadsC), 0)
}
func ClusterConfigAddBoundedLoadsCLow(builder *flatbuffers.Builder, boundedLoadsCLow flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(21, flatbuffers.UOffsetT(boundedLoadsCLow), 0)
}
func ClusterConfigAddBoundedLoadsMaxStaleTtlNs(builder *flatbuffers.Builder, boundedLoadsMaxStaleTtlNs flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(22, flatbuffers.UOffsetT(boundedLoadsMaxStaleTtlNs), 0)
}
func ClusterConfigEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
