// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CoalescedShardRef struct {
	_tab flatbuffers.Table
}

func GetRootAsCoalescedShardRef(buf []byte, offset flatbuffers.UOffsetT) *CoalescedShardRef {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CoalescedShardRef{}
	x.Init(buf, n+offset)
	return x
}

func FinishCoalescedShardRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCoalescedShardRef(buf []byte, offset flatbuffers.UOffsetT) *CoalescedShardRef {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CoalescedShardRef{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCoalescedShardRefBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CoalescedShardRef) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CoalescedShardRef) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CoalescedShardRef) CoalescedId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CoalescedShardRef) Size() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CoalescedShardRef) MutateSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *CoalescedShardRef) Etag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CoalescedShardRef) ShardKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CoalescedShardRef) Version() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *CoalescedShardRef) MutateVersion(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func CoalescedShardRefStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func CoalescedShardRefAddCoalescedId(builder *flatbuffers.Builder, coalescedId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(coalescedId), 0)
}
func CoalescedShardRefAddSize(builder *flatbuffers.Builder, size int64) {
	builder.PrependInt64Slot(1, size, 0)
}
func CoalescedShardRefAddEtag(builder *flatbuffers.Builder, etag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(etag), 0)
}
func CoalescedShardRefAddShardKey(builder *flatbuffers.Builder, shardKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(shardKey), 0)
}
func CoalescedShardRefAddVersion(builder *flatbuffers.Builder, version int32) {
	builder.PrependInt32Slot(4, version, 1)
}
func CoalescedShardRefEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
