// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import "strconv"

type CompatSeverity int8

const (
	CompatSeverityUnknown CompatSeverity = 0
	CompatSeverityHard    CompatSeverity = 1
	CompatSeveritySoft    CompatSeverity = 2
)

var EnumNamesCompatSeverity = map[CompatSeverity]string{
	CompatSeverityUnknown: "Unknown",
	CompatSeverityHard:    "Hard",
	CompatSeveritySoft:    "Soft",
}

var EnumValuesCompatSeverity = map[string]CompatSeverity{
	"Unknown": CompatSeverityUnknown,
	"Hard":    CompatSeverityHard,
	"Soft":    CompatSeveritySoft,
}

func (v CompatSeverity) String() string {
	if s, ok := EnumNamesCompatSeverity[v]; ok {
		return s
	}
	return "CompatSeverity(" + strconv.FormatInt(int64(v), 10) + ")"
}
