// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConfigEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsConfigEntry(buf []byte, offset flatbuffers.UOffsetT) *ConfigEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConfigEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishConfigEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConfigEntry(buf []byte, offset flatbuffers.UOffsetT) *ConfigEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConfigEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConfigEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConfigEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConfigEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConfigEntry) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConfigEntry) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ConfigEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ConfigEntryAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func ConfigEntryAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func ConfigEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
