// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CreateBucketCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsCreateBucketCmd(buf []byte, offset flatbuffers.UOffsetT) *CreateBucketCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreateBucketCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishCreateBucketCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCreateBucketCmd(buf []byte, offset flatbuffers.UOffsetT) *CreateBucketCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CreateBucketCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCreateBucketCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CreateBucketCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreateBucketCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CreateBucketCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CreateBucketCmd) BypassReserved() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CreateBucketCmd) MutateBypassReserved(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func CreateBucketCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CreateBucketCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func CreateBucketCmdAddBypassReserved(builder *flatbuffers.Builder, bypassReserved bool) {
	builder.PrependBoolSlot(1, bypassReserved, false)
}
func CreateBucketCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
