// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DEKRefEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsDEKRefEntry(buf []byte, offset flatbuffers.UOffsetT) *DEKRefEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DEKRefEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishDEKRefEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDEKRefEntry(buf []byte, offset flatbuffers.UOffsetT) *DEKRefEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DEKRefEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDEKRefEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DEKRefEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DEKRefEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DEKRefEntry) Gen() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DEKRefEntry) MutateGen(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *DEKRefEntry) Count() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DEKRefEntry) MutateCount(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func DEKRefEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DEKRefEntryAddGen(builder *flatbuffers.Builder, gen uint32) {
	builder.PrependUint32Slot(0, gen, 0)
}
func DEKRefEntryAddCount(builder *flatbuffers.Builder, count int64) {
	builder.PrependInt64Slot(1, count, 0)
}
func DEKRefEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
