// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeleteObjectCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteObjectCmd(buf []byte, offset flatbuffers.UOffsetT) *DeleteObjectCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteObjectCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeleteObjectCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeleteObjectCmd(buf []byte, offset flatbuffers.UOffsetT) *DeleteObjectCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeleteObjectCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeleteObjectCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeleteObjectCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteObjectCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteObjectCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeleteObjectCmd) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeleteObjectCmd) VersionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DeleteObjectCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DeleteObjectCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func DeleteObjectCmdAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func DeleteObjectCmdAddVersionId(builder *flatbuffers.Builder, versionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(versionId), 0)
}
func DeleteObjectCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
