// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeleteShardPlacementCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteShardPlacementCmd(buf []byte, offset flatbuffers.UOffsetT) *DeleteShardPlacementCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteShardPlacementCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeleteShardPlacementCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeleteShardPlacementCmd(buf []byte, offset flatbuffers.UOffsetT) *DeleteShardPlacementCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeleteShardPlacementCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeleteShardPlacementCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeleteShardPlacementCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteShardPlacementCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteShardPlacementCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeleteShardPlacementCmd) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DeleteShardPlacementCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DeleteShardPlacementCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func DeleteShardPlacementCmdAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func DeleteShardPlacementCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
