// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeleteBucketPolicyCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteBucketPolicyCmd(buf []byte, offset flatbuffers.UOffsetT) *DeleteBucketPolicyCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteBucketPolicyCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeleteBucketPolicyCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeleteBucketPolicyCmd(buf []byte, offset flatbuffers.UOffsetT) *DeleteBucketPolicyCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeleteBucketPolicyCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeleteBucketPolicyCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeleteBucketPolicyCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteBucketPolicyCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteBucketPolicyCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DeleteBucketPolicyCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func DeleteBucketPolicyCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func DeleteBucketPolicyCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
