// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DropClusterKeyAcceptCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsDropClusterKeyAcceptCmd(buf []byte, offset flatbuffers.UOffsetT) *DropClusterKeyAcceptCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DropClusterKeyAcceptCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishDropClusterKeyAcceptCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDropClusterKeyAcceptCmd(buf []byte, offset flatbuffers.UOffsetT) *DropClusterKeyAcceptCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DropClusterKeyAcceptCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDropClusterKeyAcceptCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DropClusterKeyAcceptCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DropClusterKeyAcceptCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DropClusterKeyAcceptCmd) StampedVoters(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *DropClusterKeyAcceptCmd) StampedVotersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *DropClusterKeyAcceptCmd) StampedConfigIndex() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *DropClusterKeyAcceptCmd) MutateStampedConfigIndex(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func DropClusterKeyAcceptCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DropClusterKeyAcceptCmdAddStampedVoters(builder *flatbuffers.Builder, stampedVoters flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(stampedVoters), 0)
}
func DropClusterKeyAcceptCmdStartStampedVotersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func DropClusterKeyAcceptCmdAddStampedConfigIndex(builder *flatbuffers.Builder, stampedConfigIndex uint64) {
	builder.PrependUint64Slot(1, stampedConfigIndex, 0)
}
func DropClusterKeyAcceptCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
