// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FSMValueResealDoneCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsFSMValueResealDoneCmd(buf []byte, offset flatbuffers.UOffsetT) *FSMValueResealDoneCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FSMValueResealDoneCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishFSMValueResealDoneCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFSMValueResealDoneCmd(buf []byte, offset flatbuffers.UOffsetT) *FSMValueResealDoneCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FSMValueResealDoneCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFSMValueResealDoneCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FSMValueResealDoneCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FSMValueResealDoneCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FSMValueResealDoneCmd) Gen() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FSMValueResealDoneCmd) MutateGen(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func FSMValueResealDoneCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FSMValueResealDoneCmdAddGen(builder *flatbuffers.Builder, gen uint32) {
	builder.PrependUint32Slot(0, gen, 0)
}
func FSMValueResealDoneCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
