// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IcebergIdentifier struct {
	_tab flatbuffers.Table
}

func GetRootAsIcebergIdentifier(buf []byte, offset flatbuffers.UOffsetT) *IcebergIdentifier {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IcebergIdentifier{}
	x.Init(buf, n+offset)
	return x
}

func FinishIcebergIdentifierBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsIcebergIdentifier(buf []byte, offset flatbuffers.UOffsetT) *IcebergIdentifier {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IcebergIdentifier{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedIcebergIdentifierBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *IcebergIdentifier) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IcebergIdentifier) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IcebergIdentifier) Namespace(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *IcebergIdentifier) NamespaceLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *IcebergIdentifier) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func IcebergIdentifierStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func IcebergIdentifierAddNamespace(builder *flatbuffers.Builder, namespace flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(namespace), 0)
}
func IcebergIdentifierStartNamespaceVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func IcebergIdentifierAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func IcebergIdentifierEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
