// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JoinReply struct {
	_tab flatbuffers.Table
}

func GetRootAsJoinReply(buf []byte, offset flatbuffers.UOffsetT) *JoinReply {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JoinReply{}
	x.Init(buf, n+offset)
	return x
}

func FinishJoinReplyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJoinReply(buf []byte, offset flatbuffers.UOffsetT) *JoinReply {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JoinReply{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJoinReplyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JoinReply) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JoinReply) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JoinReply) Accepted() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *JoinReply) MutateAccepted(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *JoinReply) Status() JoinStatus {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return JoinStatus(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *JoinReply) MutateStatus(n JoinStatus) bool {
	return rcv._tab.MutateInt8Slot(6, int8(n))
}

func (rcv *JoinReply) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JoinReply) LeaderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JoinReply) LeaderAddr() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *JoinReply) PeerSpkis(obj *SPKIBytes, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *JoinReply) PeerSpkisLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func JoinReplyStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func JoinReplyAddAccepted(builder *flatbuffers.Builder, accepted bool) {
	builder.PrependBoolSlot(0, accepted, false)
}
func JoinReplyAddStatus(builder *flatbuffers.Builder, status JoinStatus) {
	builder.PrependInt8Slot(1, int8(status), 0)
}
func JoinReplyAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(message), 0)
}
func JoinReplyAddLeaderId(builder *flatbuffers.Builder, leaderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(leaderId), 0)
}
func JoinReplyAddLeaderAddr(builder *flatbuffers.Builder, leaderAddr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(leaderAddr), 0)
}
func JoinReplyAddPeerSpkis(builder *flatbuffers.Builder, peerSpkis flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(peerSpkis), 0)
}
func JoinReplyStartPeerSpkisVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func JoinReplyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
