// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import "strconv"

type JoinStatus int8

const (
	JoinStatusUnknown       JoinStatus = 0
	JoinStatusOK            JoinStatus = 1
	JoinStatusAlreadyMember JoinStatus = 2
	JoinStatusNotLeader     JoinStatus = 3
	JoinStatusAddrMismatch  JoinStatus = 4
	JoinStatusClusterFull   JoinStatus = 5
	JoinStatusMixedVersion  JoinStatus = 6
	JoinStatusTimeout       JoinStatus = 7
	JoinStatusError         JoinStatus = 8
)

var EnumNamesJoinStatus = map[JoinStatus]string{
	JoinStatusUnknown:       "Unknown",
	JoinStatusOK:            "OK",
	JoinStatusAlreadyMember: "AlreadyMember",
	JoinStatusNotLeader:     "NotLeader",
	JoinStatusAddrMismatch:  "AddrMismatch",
	JoinStatusClusterFull:   "ClusterFull",
	JoinStatusMixedVersion:  "MixedVersion",
	JoinStatusTimeout:       "Timeout",
	JoinStatusError:         "Error",
}

var EnumValuesJoinStatus = map[string]JoinStatus{
	"Unknown":       JoinStatusUnknown,
	"OK":            JoinStatusOK,
	"AlreadyMember": JoinStatusAlreadyMember,
	"NotLeader":     JoinStatusNotLeader,
	"AddrMismatch":  JoinStatusAddrMismatch,
	"ClusterFull":   JoinStatusClusterFull,
	"MixedVersion":  JoinStatusMixedVersion,
	"Timeout":       JoinStatusTimeout,
	"Error":         JoinStatusError,
}

func (v JoinStatus) String() string {
	if s, ok := EnumNamesJoinStatus[v]; ok {
		return s
	}
	return "JoinStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
