// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KEKStatusEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsKEKStatusEntry(buf []byte, offset flatbuffers.UOffsetT) *KEKStatusEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KEKStatusEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishKEKStatusEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKEKStatusEntry(buf []byte, offset flatbuffers.UOffsetT) *KEKStatusEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KEKStatusEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKEKStatusEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KEKStatusEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KEKStatusEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KEKStatusEntry) Version() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KEKStatusEntry) MutateVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *KEKStatusEntry) Status() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KEKStatusEntry) MutateStatus(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *KEKStatusEntry) RetireCommitIndex() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KEKStatusEntry) MutateRetireCommitIndex(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func KEKStatusEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func KEKStatusEntryAddVersion(builder *flatbuffers.Builder, version uint32) {
	builder.PrependUint32Slot(0, version, 0)
}
func KEKStatusEntryAddStatus(builder *flatbuffers.Builder, status byte) {
	builder.PrependByteSlot(1, status, 0)
}
func KEKStatusEntryAddRetireCommitIndex(builder *flatbuffers.Builder, retireCommitIndex uint64) {
	builder.PrependUint64Slot(2, retireCommitIndex, 0)
}
func KEKStatusEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
