// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaProtocolCredentialRotateCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaProtocolCredentialRotateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialRotateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaProtocolCredentialRotateCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaProtocolCredentialRotateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaProtocolCredentialRotateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialRotateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaProtocolCredentialRotateCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaProtocolCredentialRotateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaProtocolCredentialRotateCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaProtocolCredentialRotateCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaProtocolCredentialRotateCmd) RequestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialRotateCmd) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialRotateCmd) SecretHash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaProtocolCredentialRotateCmd) SecretHashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaProtocolCredentialRotateCmd) SecretHashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialRotateCmd) MutateSecretHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaProtocolCredentialRotateCmd) SecretHint() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialRotateCmd) RotatedAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaProtocolCredentialRotateCmd) MutateRotatedAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func MetaProtocolCredentialRotateCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MetaProtocolCredentialRotateCmdAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requestId), 0)
}
func MetaProtocolCredentialRotateCmdAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(id), 0)
}
func MetaProtocolCredentialRotateCmdAddSecretHash(builder *flatbuffers.Builder, secretHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(secretHash), 0)
}
func MetaProtocolCredentialRotateCmdStartSecretHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaProtocolCredentialRotateCmdAddSecretHint(builder *flatbuffers.Builder, secretHint flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(secretHint), 0)
}
func MetaProtocolCredentialRotateCmdAddRotatedAtUnixNanos(builder *flatbuffers.Builder, rotatedAtUnixNanos int64) {
	builder.PrependInt64Slot(4, rotatedAtUnixNanos, 0)
}
func MetaProtocolCredentialRotateCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
