// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaAbortPlanCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaAbortPlanCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaAbortPlanCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaAbortPlanCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaAbortPlanCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaAbortPlanCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaAbortPlanCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaAbortPlanCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaAbortPlanCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaAbortPlanCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaAbortPlanCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaAbortPlanCmd) PlanId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaAbortPlanCmd) Reason() AbortPlanReason {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return AbortPlanReason(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MetaAbortPlanCmd) MutateReason(n AbortPlanReason) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func MetaAbortPlanCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaAbortPlanCmdAddPlanId(builder *flatbuffers.Builder, planId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(planId), 0)
}
func MetaAbortPlanCmdAddReason(builder *flatbuffers.Builder, reason AbortPlanReason) {
	builder.PrependByteSlot(1, byte(reason), 0)
}
func MetaAbortPlanCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
