// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaConfigPutCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaConfigPutCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaConfigPutCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaConfigPutCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaConfigPutCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaConfigPutCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaConfigPutCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaConfigPutCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaConfigPutCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaConfigPutCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaConfigPutCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaConfigPutCmd) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaConfigPutCmd) Value() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaConfigPutCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaConfigPutCmdAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func MetaConfigPutCmdAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(value), 0)
}
func MetaConfigPutCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
