// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaIcebergDeleteNamespaceCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaIcebergDeleteNamespaceCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaIcebergDeleteNamespaceCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaIcebergDeleteNamespaceCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaIcebergDeleteNamespaceCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaIcebergDeleteNamespaceCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaIcebergDeleteNamespaceCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaIcebergDeleteNamespaceCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaIcebergDeleteNamespaceCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaIcebergDeleteNamespaceCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaIcebergDeleteNamespaceCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaIcebergDeleteNamespaceCmd) RequestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaIcebergDeleteNamespaceCmd) Namespace(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *MetaIcebergDeleteNamespaceCmd) NamespaceLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MetaIcebergDeleteNamespaceCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaIcebergDeleteNamespaceCmdAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requestId), 0)
}
func MetaIcebergDeleteNamespaceCmdAddNamespace(builder *flatbuffers.Builder, namespace flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(namespace), 0)
}
func MetaIcebergDeleteNamespaceCmdStartNamespaceVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MetaIcebergDeleteNamespaceCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
