// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaCmd) Type() MetaCmdType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return MetaCmdType(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MetaCmd) MutateType(n MetaCmdType) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *MetaCmd) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaCmd) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaCmd) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaCmd) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func MetaCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaCmdAddType(builder *flatbuffers.Builder, type_ MetaCmdType) {
	builder.PrependByteSlot(0, byte(type_), 0)
}
func MetaCmdAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(data), 0)
}
func MetaCmdStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
