// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaProposeRebalancePlanCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaProposeRebalancePlanCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProposeRebalancePlanCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaProposeRebalancePlanCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaProposeRebalancePlanCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaProposeRebalancePlanCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProposeRebalancePlanCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaProposeRebalancePlanCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaProposeRebalancePlanCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaProposeRebalancePlanCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaProposeRebalancePlanCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaProposeRebalancePlanCmd) Plan(obj *RebalancePlan) *RebalancePlan {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(RebalancePlan)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MetaProposeRebalancePlanCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaProposeRebalancePlanCmdAddPlan(builder *flatbuffers.Builder, plan flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(plan), 0)
}
func MetaProposeRebalancePlanCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
