// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaProtocolCredentialCreateCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaProtocolCredentialCreateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialCreateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaProtocolCredentialCreateCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaProtocolCredentialCreateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaProtocolCredentialCreateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialCreateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaProtocolCredentialCreateCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaProtocolCredentialCreateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaProtocolCredentialCreateCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaProtocolCredentialCreateCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaProtocolCredentialCreateCmd) RequestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialCreateCmd) Row(obj *MetaProtocolCredentialEntry) *MetaProtocolCredentialEntry {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MetaProtocolCredentialEntry)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MetaProtocolCredentialCreateCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaProtocolCredentialCreateCmdAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requestId), 0)
}
func MetaProtocolCredentialCreateCmdAddRow(builder *flatbuffers.Builder, row flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(row), 0)
}
func MetaProtocolCredentialCreateCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
