// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaCapabilityActivateCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaCapabilityActivateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaCapabilityActivateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaCapabilityActivateCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaCapabilityActivateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaCapabilityActivateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaCapabilityActivateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaCapabilityActivateCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaCapabilityActivateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaCapabilityActivateCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaCapabilityActivateCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaCapabilityActivateCmd) Capability() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaCapabilityActivateCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaCapabilityActivateCmdAddCapability(builder *flatbuffers.Builder, capability flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(capability), 0)
}
func MetaCapabilityActivateCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
