// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaRotateKeySwitchCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaRotateKeySwitchCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRotateKeySwitchCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaRotateKeySwitchCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaRotateKeySwitchCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaRotateKeySwitchCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRotateKeySwitchCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaRotateKeySwitchCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaRotateKeySwitchCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaRotateKeySwitchCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaRotateKeySwitchCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaRotateKeySwitchCmd) RotationId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaRotateKeySwitchCmd) RotationIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaRotateKeySwitchCmd) RotationIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaRotateKeySwitchCmd) MutateRotationId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func MetaRotateKeySwitchCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaRotateKeySwitchCmdAddRotationId(builder *flatbuffers.Builder, rotationId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(rotationId), 0)
}
func MetaRotateKeySwitchCmdStartRotationIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaRotateKeySwitchCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
