// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaProtocolCredentialRequestEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaProtocolCredentialRequestEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialRequestEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaProtocolCredentialRequestEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaProtocolCredentialRequestEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaProtocolCredentialRequestEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialRequestEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaProtocolCredentialRequestEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaProtocolCredentialRequestEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaProtocolCredentialRequestEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaProtocolCredentialRequestEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaProtocolCredentialRequestEntry) RequestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialRequestEntry) Operation() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialRequestEntry) CredentialId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialRequestEntry) PayloadHash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaProtocolCredentialRequestEntry) PayloadHashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaProtocolCredentialRequestEntry) PayloadHashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialRequestEntry) MutatePayloadHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func MetaProtocolCredentialRequestEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MetaProtocolCredentialRequestEntryAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requestId), 0)
}
func MetaProtocolCredentialRequestEntryAddOperation(builder *flatbuffers.Builder, operation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(operation), 0)
}
func MetaProtocolCredentialRequestEntryAddCredentialId(builder *flatbuffers.Builder, credentialId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(credentialId), 0)
}
func MetaProtocolCredentialRequestEntryAddPayloadHash(builder *flatbuffers.Builder, payloadHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(payloadHash), 0)
}
func MetaProtocolCredentialRequestEntryStartPayloadHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaProtocolCredentialRequestEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
