// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaRegisterPendingLearnerCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaRegisterPendingLearnerCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRegisterPendingLearnerCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaRegisterPendingLearnerCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaRegisterPendingLearnerCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaRegisterPendingLearnerCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRegisterPendingLearnerCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaRegisterPendingLearnerCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaRegisterPendingLearnerCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaRegisterPendingLearnerCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaRegisterPendingLearnerCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaRegisterPendingLearnerCmd) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaRegisterPendingLearnerCmd) Spki(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaRegisterPendingLearnerCmd) SpkiLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaRegisterPendingLearnerCmd) SpkiBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaRegisterPendingLearnerCmd) MutateSpki(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaRegisterPendingLearnerCmd) Address() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaRegisterPendingLearnerCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MetaRegisterPendingLearnerCmdAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func MetaRegisterPendingLearnerCmdAddSpki(builder *flatbuffers.Builder, spki flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(spki), 0)
}
func MetaRegisterPendingLearnerCmdStartSpkiVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaRegisterPendingLearnerCmdAddAddress(builder *flatbuffers.Builder, address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(address), 0)
}
func MetaRegisterPendingLearnerCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
