// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaJWTSigningKeyRotateCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaJWTSigningKeyRotateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaJWTSigningKeyRotateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaJWTSigningKeyRotateCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaJWTSigningKeyRotateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaJWTSigningKeyRotateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaJWTSigningKeyRotateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaJWTSigningKeyRotateCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaJWTSigningKeyRotateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaJWTSigningKeyRotateCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaJWTSigningKeyRotateCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaJWTSigningKeyRotateCmd) Kid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaJWTSigningKeyRotateCmd) WrappedSecret(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaJWTSigningKeyRotateCmd) WrappedSecretLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaJWTSigningKeyRotateCmd) WrappedSecretBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaJWTSigningKeyRotateCmd) MutateWrappedSecret(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaJWTSigningKeyRotateCmd) DekGen() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaJWTSigningKeyRotateCmd) MutateDekGen(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *MetaJWTSigningKeyRotateCmd) DemotedAtUnix() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaJWTSigningKeyRotateCmd) MutateDemotedAtUnix(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func MetaJWTSigningKeyRotateCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MetaJWTSigningKeyRotateCmdAddKid(builder *flatbuffers.Builder, kid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(kid), 0)
}
func MetaJWTSigningKeyRotateCmdAddWrappedSecret(builder *flatbuffers.Builder, wrappedSecret flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(wrappedSecret), 0)
}
func MetaJWTSigningKeyRotateCmdStartWrappedSecretVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaJWTSigningKeyRotateCmdAddDekGen(builder *flatbuffers.Builder, dekGen uint32) {
	builder.PrependUint32Slot(2, dekGen, 0)
}
func MetaJWTSigningKeyRotateCmdAddDemotedAtUnix(builder *flatbuffers.Builder, demotedAtUnix int64) {
	builder.PrependInt64Slot(3, demotedAtUnix, 0)
}
func MetaJWTSigningKeyRotateCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
