// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaInviteConsumeCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaInviteConsumeCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaInviteConsumeCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaInviteConsumeCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaInviteConsumeCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaInviteConsumeCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaInviteConsumeCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaInviteConsumeCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaInviteConsumeCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaInviteConsumeCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaInviteConsumeCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaInviteConsumeCmd) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaInviteConsumeCmd) ConsumedAtNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaInviteConsumeCmd) MutateConsumedAtNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func MetaInviteConsumeCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaInviteConsumeCmdAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func MetaInviteConsumeCmdAddConsumedAtNanos(builder *flatbuffers.Builder, consumedAtNanos int64) {
	builder.PrependInt64Slot(1, consumedAtNanos, 0)
}
func MetaInviteConsumeCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
