// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaDEKVersionPruneCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaDEKVersionPruneCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaDEKVersionPruneCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaDEKVersionPruneCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaDEKVersionPruneCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaDEKVersionPruneCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaDEKVersionPruneCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaDEKVersionPruneCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaDEKVersionPruneCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaDEKVersionPruneCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaDEKVersionPruneCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaDEKVersionPruneCmd) Gen() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaDEKVersionPruneCmd) MutateGen(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func MetaDEKVersionPruneCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaDEKVersionPruneCmdAddGen(builder *flatbuffers.Builder, gen uint32) {
	builder.PrependUint32Slot(0, gen, 0)
}
func MetaDEKVersionPruneCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
