// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaGroupDeleteCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaGroupDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaGroupDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaGroupDeleteCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaGroupDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaGroupDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaGroupDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaGroupDeleteCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaGroupDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaGroupDeleteCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaGroupDeleteCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaGroupDeleteCmd) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaGroupDeleteCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaGroupDeleteCmdAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func MetaGroupDeleteCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
