// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaIAMPolicyAttachGroupEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaIAMPolicyAttachGroupEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaIAMPolicyAttachGroupEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaIAMPolicyAttachGroupEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaIAMPolicyAttachGroupEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaIAMPolicyAttachGroupEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaIAMPolicyAttachGroupEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaIAMPolicyAttachGroupEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaIAMPolicyAttachGroupEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaIAMPolicyAttachGroupEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaIAMPolicyAttachGroupEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaIAMPolicyAttachGroupEntry) Group() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaIAMPolicyAttachGroupEntry) Policies(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *MetaIAMPolicyAttachGroupEntry) PoliciesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func MetaIAMPolicyAttachGroupEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaIAMPolicyAttachGroupEntryAddGroup(builder *flatbuffers.Builder, group flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(group), 0)
}
func MetaIAMPolicyAttachGroupEntryAddPolicies(builder *flatbuffers.Builder, policies flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(policies), 0)
}
func MetaIAMPolicyAttachGroupEntryStartPoliciesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MetaIAMPolicyAttachGroupEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
