// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaPutShardGroupCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaPutShardGroupCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPutShardGroupCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaPutShardGroupCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaPutShardGroupCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaPutShardGroupCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPutShardGroupCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaPutShardGroupCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaPutShardGroupCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaPutShardGroupCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaPutShardGroupCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaPutShardGroupCmd) Group(obj *ShardGroupEntry) *ShardGroupEntry {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ShardGroupEntry)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MetaPutShardGroupCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaPutShardGroupCmdAddGroup(builder *flatbuffers.Builder, group flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(group), 0)
}
func MetaPutShardGroupCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
