// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaPolicyDeleteCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaPolicyDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPolicyDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaPolicyDeleteCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaPolicyDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaPolicyDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPolicyDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaPolicyDeleteCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaPolicyDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaPolicyDeleteCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaPolicyDeleteCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaPolicyDeleteCmd) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaPolicyDeleteCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaPolicyDeleteCmdAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func MetaPolicyDeleteCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
