// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaPutIndexGroupCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaPutIndexGroupCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPutIndexGroupCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaPutIndexGroupCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaPutIndexGroupCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaPutIndexGroupCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPutIndexGroupCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaPutIndexGroupCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaPutIndexGroupCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaPutIndexGroupCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaPutIndexGroupCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaPutIndexGroupCmd) Group(obj *IndexGroupEntry) *IndexGroupEntry {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(IndexGroupEntry)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MetaPutIndexGroupCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaPutIndexGroupCmdAddGroup(builder *flatbuffers.Builder, group flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(group), 0)
}
func MetaPutIndexGroupCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
