// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaDeleteObjectIndexCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaDeleteObjectIndexCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaDeleteObjectIndexCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaDeleteObjectIndexCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaDeleteObjectIndexCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaDeleteObjectIndexCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaDeleteObjectIndexCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaDeleteObjectIndexCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaDeleteObjectIndexCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaDeleteObjectIndexCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaDeleteObjectIndexCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaDeleteObjectIndexCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaDeleteObjectIndexCmd) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaDeleteObjectIndexCmd) VersionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaDeleteObjectIndexCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MetaDeleteObjectIndexCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func MetaDeleteObjectIndexCmdAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func MetaDeleteObjectIndexCmdAddVersionId(builder *flatbuffers.Builder, versionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(versionId), 0)
}
func MetaDeleteObjectIndexCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
