// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaProtocolCredentialLastUsedCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaProtocolCredentialLastUsedCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialLastUsedCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaProtocolCredentialLastUsedCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaProtocolCredentialLastUsedCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaProtocolCredentialLastUsedCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialLastUsedCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaProtocolCredentialLastUsedCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaProtocolCredentialLastUsedCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaProtocolCredentialLastUsedCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaProtocolCredentialLastUsedCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaProtocolCredentialLastUsedCmd) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialLastUsedCmd) LastUsedAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaProtocolCredentialLastUsedCmd) MutateLastUsedAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func MetaProtocolCredentialLastUsedCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaProtocolCredentialLastUsedCmdAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func MetaProtocolCredentialLastUsedCmdAddLastUsedAtUnixNanos(builder *flatbuffers.Builder, lastUsedAtUnixNanos int64) {
	builder.PrependInt64Slot(1, lastUsedAtUnixNanos, 0)
}
func MetaProtocolCredentialLastUsedCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
