// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import "strconv"

type MetaCmdType byte

const (
	MetaCmdTypeNoOp                         MetaCmdType = 0
	MetaCmdTypeAddNode                      MetaCmdType = 1
	MetaCmdTypeRemoveNode                   MetaCmdType = 2
	MetaCmdTypePutShardGroup                MetaCmdType = 3
	MetaCmdTypeSetActivePlan                MetaCmdType = 4
	MetaCmdTypePutBucketAssignment          MetaCmdType = 5
	MetaCmdTypeSetLoadSnapshot              MetaCmdType = 6
	MetaCmdTypeProposeRebalancePlan         MetaCmdType = 7
	MetaCmdTypeAbortPlan                    MetaCmdType = 8
	MetaCmdTypeIcebergCreateNamespace       MetaCmdType = 9
	MetaCmdTypeIcebergDeleteNamespace       MetaCmdType = 10
	MetaCmdTypeIcebergCreateTable           MetaCmdType = 11
	MetaCmdTypeIcebergCommitTable           MetaCmdType = 12
	MetaCmdTypeIcebergDeleteTable           MetaCmdType = 13
	MetaCmdTypeRotateKeyBegin               MetaCmdType = 14
	MetaCmdTypeRotateKeySwitch              MetaCmdType = 15
	MetaCmdTypeRotateKeyDrop                MetaCmdType = 16
	MetaCmdTypeRotateKeyAbort               MetaCmdType = 17
	MetaCmdTypeScrubTrigger                 MetaCmdType = 18
	MetaCmdTypePutObjectIndex               MetaCmdType = 19
	MetaCmdTypeDeleteObjectIndex            MetaCmdType = 20
	MetaCmdTypeIAMSACreate                  MetaCmdType = 21
	MetaCmdTypeIAMSADelete                  MetaCmdType = 22
	MetaCmdTypeIAMKeyCreate                 MetaCmdType = 23
	MetaCmdTypeIAMKeyRevoke                 MetaCmdType = 24
	MetaCmdTypeIAMGrantPut                  MetaCmdType = 25
	MetaCmdTypeIAMGrantDelete               MetaCmdType = 26
	MetaCmdTypeIAMGrantWildcardPut          MetaCmdType = 27
	MetaCmdTypeIAMAuthEnable                MetaCmdType = 28
	MetaCmdTypeIAMGrantWildcardDelete       MetaCmdType = 29
	MetaCmdTypeIAMKeyCreateScoped           MetaCmdType = 30
	MetaCmdTypeIAMInitFirstSA               MetaCmdType = 31
	MetaCmdTypeIAMBucketUpstreamPut         MetaCmdType = 32
	MetaCmdTypeIAMBucketUpstreamDelete      MetaCmdType = 33
	MetaCmdTypeBucketLifecyclePut           MetaCmdType = 34
	MetaCmdTypeBucketLifecycleDelete        MetaCmdType = 35
	MetaCmdTypeClusterConfigPatch           MetaCmdType = 36
	MetaCmdTypeMigrationJobStart            MetaCmdType = 37
	MetaCmdTypeMigrationJobDone             MetaCmdType = 38
	MetaCmdTypeMigrationJobFailed           MetaCmdType = 39
	MetaCmdTypeNfsExportUpsert              MetaCmdType = 40
	MetaCmdTypeNfsExportDelete              MetaCmdType = 41
	MetaCmdTypeNfsExportBucketDeleteCascade MetaCmdType = 42
	MetaCmdTypeCapabilityActivate           MetaCmdType = 43
	MetaCmdTypeMigrationCutover             MetaCmdType = 44
	MetaCmdTypeNfsExportCreate              MetaCmdType = 45
	MetaCmdTypeConfigPut                    MetaCmdType = 46
	MetaCmdTypeConfigDelete                 MetaCmdType = 47
	MetaCmdTypeDEKRotate                    MetaCmdType = 48
	MetaCmdTypeDEKVersionPrune              MetaCmdType = 49
	MetaCmdTypePolicyPut                    MetaCmdType = 50
	MetaCmdTypePolicyDelete                 MetaCmdType = 51
	MetaCmdTypeGroupPut                     MetaCmdType = 52
	MetaCmdTypeGroupDelete                  MetaCmdType = 53
	MetaCmdTypeGroupMemberPut               MetaCmdType = 54
	MetaCmdTypeGroupMemberDelete            MetaCmdType = 55
	MetaCmdTypePolicyAttachToSAPut          MetaCmdType = 56
	MetaCmdTypePolicyAttachToSADelete       MetaCmdType = 57
	MetaCmdTypePolicyAttachToGroupPut       MetaCmdType = 58
	MetaCmdTypePolicyAttachToGroupDelete    MetaCmdType = 59
	MetaCmdTypeBucketPolicyPut              MetaCmdType = 60
	MetaCmdTypeBucketPolicyDelete           MetaCmdType = 61
	MetaCmdTypeCreateBucketWithPolicyAttach MetaCmdType = 62
	MetaCmdTypeJWTSigningKeyRotate          MetaCmdType = 63
	MetaCmdTypeJWTSigningKeyPrune           MetaCmdType = 64
	MetaCmdTypeMountSACreate                MetaCmdType = 65
	MetaCmdTypeMountSADelete                MetaCmdType = 66
	MetaCmdTypeMountSAAttachPolicy          MetaCmdType = 67
	MetaCmdTypeMountSADetachPolicy          MetaCmdType = 68
	MetaCmdTypeKEKRotate                    MetaCmdType = 69
	MetaCmdTypeKEKRetire                    MetaCmdType = 70
	MetaCmdTypeKEKPrune                     MetaCmdType = 71
	MetaCmdTypeDEKReplicatedRotate          MetaCmdType = 72
	MetaCmdTypeInviteMint                   MetaCmdType = 73
	MetaCmdTypeInviteConsume                MetaCmdType = 74
	MetaCmdTypeRegisterPendingLearner       MetaCmdType = 75
	MetaCmdTypePromoteMember                MetaCmdType = 76
	MetaCmdTypeRevokePeer                   MetaCmdType = 77
)

var EnumNamesMetaCmdType = map[MetaCmdType]string{
	MetaCmdTypeNoOp:                         "NoOp",
	MetaCmdTypeAddNode:                      "AddNode",
	MetaCmdTypeRemoveNode:                   "RemoveNode",
	MetaCmdTypePutShardGroup:                "PutShardGroup",
	MetaCmdTypeSetActivePlan:                "SetActivePlan",
	MetaCmdTypePutBucketAssignment:          "PutBucketAssignment",
	MetaCmdTypeSetLoadSnapshot:              "SetLoadSnapshot",
	MetaCmdTypeProposeRebalancePlan:         "ProposeRebalancePlan",
	MetaCmdTypeAbortPlan:                    "AbortPlan",
	MetaCmdTypeIcebergCreateNamespace:       "IcebergCreateNamespace",
	MetaCmdTypeIcebergDeleteNamespace:       "IcebergDeleteNamespace",
	MetaCmdTypeIcebergCreateTable:           "IcebergCreateTable",
	MetaCmdTypeIcebergCommitTable:           "IcebergCommitTable",
	MetaCmdTypeIcebergDeleteTable:           "IcebergDeleteTable",
	MetaCmdTypeRotateKeyBegin:               "RotateKeyBegin",
	MetaCmdTypeRotateKeySwitch:              "RotateKeySwitch",
	MetaCmdTypeRotateKeyDrop:                "RotateKeyDrop",
	MetaCmdTypeRotateKeyAbort:               "RotateKeyAbort",
	MetaCmdTypeScrubTrigger:                 "ScrubTrigger",
	MetaCmdTypePutObjectIndex:               "PutObjectIndex",
	MetaCmdTypeDeleteObjectIndex:            "DeleteObjectIndex",
	MetaCmdTypeIAMSACreate:                  "IAMSACreate",
	MetaCmdTypeIAMSADelete:                  "IAMSADelete",
	MetaCmdTypeIAMKeyCreate:                 "IAMKeyCreate",
	MetaCmdTypeIAMKeyRevoke:                 "IAMKeyRevoke",
	MetaCmdTypeIAMGrantPut:                  "IAMGrantPut",
	MetaCmdTypeIAMGrantDelete:               "IAMGrantDelete",
	MetaCmdTypeIAMGrantWildcardPut:          "IAMGrantWildcardPut",
	MetaCmdTypeIAMAuthEnable:                "IAMAuthEnable",
	MetaCmdTypeIAMGrantWildcardDelete:       "IAMGrantWildcardDelete",
	MetaCmdTypeIAMKeyCreateScoped:           "IAMKeyCreateScoped",
	MetaCmdTypeIAMInitFirstSA:               "IAMInitFirstSA",
	MetaCmdTypeIAMBucketUpstreamPut:         "IAMBucketUpstreamPut",
	MetaCmdTypeIAMBucketUpstreamDelete:      "IAMBucketUpstreamDelete",
	MetaCmdTypeBucketLifecyclePut:           "BucketLifecyclePut",
	MetaCmdTypeBucketLifecycleDelete:        "BucketLifecycleDelete",
	MetaCmdTypeClusterConfigPatch:           "ClusterConfigPatch",
	MetaCmdTypeMigrationJobStart:            "MigrationJobStart",
	MetaCmdTypeMigrationJobDone:             "MigrationJobDone",
	MetaCmdTypeMigrationJobFailed:           "MigrationJobFailed",
	MetaCmdTypeNfsExportUpsert:              "NfsExportUpsert",
	MetaCmdTypeNfsExportDelete:              "NfsExportDelete",
	MetaCmdTypeNfsExportBucketDeleteCascade: "NfsExportBucketDeleteCascade",
	MetaCmdTypeCapabilityActivate:           "CapabilityActivate",
	MetaCmdTypeMigrationCutover:             "MigrationCutover",
	MetaCmdTypeNfsExportCreate:              "NfsExportCreate",
	MetaCmdTypeConfigPut:                    "ConfigPut",
	MetaCmdTypeConfigDelete:                 "ConfigDelete",
	MetaCmdTypeDEKRotate:                    "DEKRotate",
	MetaCmdTypeDEKVersionPrune:              "DEKVersionPrune",
	MetaCmdTypePolicyPut:                    "PolicyPut",
	MetaCmdTypePolicyDelete:                 "PolicyDelete",
	MetaCmdTypeGroupPut:                     "GroupPut",
	MetaCmdTypeGroupDelete:                  "GroupDelete",
	MetaCmdTypeGroupMemberPut:               "GroupMemberPut",
	MetaCmdTypeGroupMemberDelete:            "GroupMemberDelete",
	MetaCmdTypePolicyAttachToSAPut:          "PolicyAttachToSAPut",
	MetaCmdTypePolicyAttachToSADelete:       "PolicyAttachToSADelete",
	MetaCmdTypePolicyAttachToGroupPut:       "PolicyAttachToGroupPut",
	MetaCmdTypePolicyAttachToGroupDelete:    "PolicyAttachToGroupDelete",
	MetaCmdTypeBucketPolicyPut:              "BucketPolicyPut",
	MetaCmdTypeBucketPolicyDelete:           "BucketPolicyDelete",
	MetaCmdTypeCreateBucketWithPolicyAttach: "CreateBucketWithPolicyAttach",
	MetaCmdTypeJWTSigningKeyRotate:          "JWTSigningKeyRotate",
	MetaCmdTypeJWTSigningKeyPrune:           "JWTSigningKeyPrune",
	MetaCmdTypeMountSACreate:                "MountSACreate",
	MetaCmdTypeMountSADelete:                "MountSADelete",
	MetaCmdTypeMountSAAttachPolicy:          "MountSAAttachPolicy",
	MetaCmdTypeMountSADetachPolicy:          "MountSADetachPolicy",
	MetaCmdTypeKEKRotate:                    "KEKRotate",
	MetaCmdTypeKEKRetire:                    "KEKRetire",
	MetaCmdTypeKEKPrune:                     "KEKPrune",
	MetaCmdTypeDEKReplicatedRotate:          "DEKReplicatedRotate",
	MetaCmdTypeInviteMint:                   "InviteMint",
	MetaCmdTypeInviteConsume:                "InviteConsume",
	MetaCmdTypeRegisterPendingLearner:       "RegisterPendingLearner",
	MetaCmdTypePromoteMember:                "PromoteMember",
	MetaCmdTypeRevokePeer:                   "RevokePeer",
}

var EnumValuesMetaCmdType = map[string]MetaCmdType{
	"NoOp":                         MetaCmdTypeNoOp,
	"AddNode":                      MetaCmdTypeAddNode,
	"RemoveNode":                   MetaCmdTypeRemoveNode,
	"PutShardGroup":                MetaCmdTypePutShardGroup,
	"SetActivePlan":                MetaCmdTypeSetActivePlan,
	"PutBucketAssignment":          MetaCmdTypePutBucketAssignment,
	"SetLoadSnapshot":              MetaCmdTypeSetLoadSnapshot,
	"ProposeRebalancePlan":         MetaCmdTypeProposeRebalancePlan,
	"AbortPlan":                    MetaCmdTypeAbortPlan,
	"IcebergCreateNamespace":       MetaCmdTypeIcebergCreateNamespace,
	"IcebergDeleteNamespace":       MetaCmdTypeIcebergDeleteNamespace,
	"IcebergCreateTable":           MetaCmdTypeIcebergCreateTable,
	"IcebergCommitTable":           MetaCmdTypeIcebergCommitTable,
	"IcebergDeleteTable":           MetaCmdTypeIcebergDeleteTable,
	"RotateKeyBegin":               MetaCmdTypeRotateKeyBegin,
	"RotateKeySwitch":              MetaCmdTypeRotateKeySwitch,
	"RotateKeyDrop":                MetaCmdTypeRotateKeyDrop,
	"RotateKeyAbort":               MetaCmdTypeRotateKeyAbort,
	"ScrubTrigger":                 MetaCmdTypeScrubTrigger,
	"PutObjectIndex":               MetaCmdTypePutObjectIndex,
	"DeleteObjectIndex":            MetaCmdTypeDeleteObjectIndex,
	"IAMSACreate":                  MetaCmdTypeIAMSACreate,
	"IAMSADelete":                  MetaCmdTypeIAMSADelete,
	"IAMKeyCreate":                 MetaCmdTypeIAMKeyCreate,
	"IAMKeyRevoke":                 MetaCmdTypeIAMKeyRevoke,
	"IAMGrantPut":                  MetaCmdTypeIAMGrantPut,
	"IAMGrantDelete":               MetaCmdTypeIAMGrantDelete,
	"IAMGrantWildcardPut":          MetaCmdTypeIAMGrantWildcardPut,
	"IAMAuthEnable":                MetaCmdTypeIAMAuthEnable,
	"IAMGrantWildcardDelete":       MetaCmdTypeIAMGrantWildcardDelete,
	"IAMKeyCreateScoped":           MetaCmdTypeIAMKeyCreateScoped,
	"IAMInitFirstSA":               MetaCmdTypeIAMInitFirstSA,
	"IAMBucketUpstreamPut":         MetaCmdTypeIAMBucketUpstreamPut,
	"IAMBucketUpstreamDelete":      MetaCmdTypeIAMBucketUpstreamDelete,
	"BucketLifecyclePut":           MetaCmdTypeBucketLifecyclePut,
	"BucketLifecycleDelete":        MetaCmdTypeBucketLifecycleDelete,
	"ClusterConfigPatch":           MetaCmdTypeClusterConfigPatch,
	"MigrationJobStart":            MetaCmdTypeMigrationJobStart,
	"MigrationJobDone":             MetaCmdTypeMigrationJobDone,
	"MigrationJobFailed":           MetaCmdTypeMigrationJobFailed,
	"NfsExportUpsert":              MetaCmdTypeNfsExportUpsert,
	"NfsExportDelete":              MetaCmdTypeNfsExportDelete,
	"NfsExportBucketDeleteCascade": MetaCmdTypeNfsExportBucketDeleteCascade,
	"CapabilityActivate":           MetaCmdTypeCapabilityActivate,
	"MigrationCutover":             MetaCmdTypeMigrationCutover,
	"NfsExportCreate":              MetaCmdTypeNfsExportCreate,
	"ConfigPut":                    MetaCmdTypeConfigPut,
	"ConfigDelete":                 MetaCmdTypeConfigDelete,
	"DEKRotate":                    MetaCmdTypeDEKRotate,
	"DEKVersionPrune":              MetaCmdTypeDEKVersionPrune,
	"PolicyPut":                    MetaCmdTypePolicyPut,
	"PolicyDelete":                 MetaCmdTypePolicyDelete,
	"GroupPut":                     MetaCmdTypeGroupPut,
	"GroupDelete":                  MetaCmdTypeGroupDelete,
	"GroupMemberPut":               MetaCmdTypeGroupMemberPut,
	"GroupMemberDelete":            MetaCmdTypeGroupMemberDelete,
	"PolicyAttachToSAPut":          MetaCmdTypePolicyAttachToSAPut,
	"PolicyAttachToSADelete":       MetaCmdTypePolicyAttachToSADelete,
	"PolicyAttachToGroupPut":       MetaCmdTypePolicyAttachToGroupPut,
	"PolicyAttachToGroupDelete":    MetaCmdTypePolicyAttachToGroupDelete,
	"BucketPolicyPut":              MetaCmdTypeBucketPolicyPut,
	"BucketPolicyDelete":           MetaCmdTypeBucketPolicyDelete,
	"CreateBucketWithPolicyAttach": MetaCmdTypeCreateBucketWithPolicyAttach,
	"JWTSigningKeyRotate":          MetaCmdTypeJWTSigningKeyRotate,
	"JWTSigningKeyPrune":           MetaCmdTypeJWTSigningKeyPrune,
	"MountSACreate":                MetaCmdTypeMountSACreate,
	"MountSADelete":                MetaCmdTypeMountSADelete,
	"MountSAAttachPolicy":          MetaCmdTypeMountSAAttachPolicy,
	"MountSADetachPolicy":          MetaCmdTypeMountSADetachPolicy,
	"KEKRotate":                    MetaCmdTypeKEKRotate,
	"KEKRetire":                    MetaCmdTypeKEKRetire,
	"KEKPrune":                     MetaCmdTypeKEKPrune,
	"DEKReplicatedRotate":          MetaCmdTypeDEKReplicatedRotate,
	"InviteMint":                   MetaCmdTypeInviteMint,
	"InviteConsume":                MetaCmdTypeInviteConsume,
	"RegisterPendingLearner":       MetaCmdTypeRegisterPendingLearner,
	"PromoteMember":                MetaCmdTypePromoteMember,
	"RevokePeer":                   MetaCmdTypeRevokePeer,
}

func (v MetaCmdType) String() string {
	if s, ok := EnumNamesMetaCmdType[v]; ok {
		return s
	}
	return "MetaCmdType(" + strconv.FormatInt(int64(v), 10) + ")"
}
