// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaRotateKeyDropCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaRotateKeyDropCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRotateKeyDropCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaRotateKeyDropCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaRotateKeyDropCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaRotateKeyDropCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRotateKeyDropCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaRotateKeyDropCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaRotateKeyDropCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaRotateKeyDropCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaRotateKeyDropCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaRotateKeyDropCmd) RotationId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaRotateKeyDropCmd) RotationIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaRotateKeyDropCmd) RotationIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaRotateKeyDropCmd) MutateRotationId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaRotateKeyDropCmd) GraceUntil() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaRotateKeyDropCmd) MutateGraceUntil(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func MetaRotateKeyDropCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaRotateKeyDropCmdAddRotationId(builder *flatbuffers.Builder, rotationId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(rotationId), 0)
}
func MetaRotateKeyDropCmdStartRotationIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaRotateKeyDropCmdAddGraceUntil(builder *flatbuffers.Builder, graceUntil int64) {
	builder.PrependInt64Slot(1, graceUntil, 0)
}
func MetaRotateKeyDropCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
