// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaRotateKeyBeginCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaRotateKeyBeginCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRotateKeyBeginCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaRotateKeyBeginCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaRotateKeyBeginCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaRotateKeyBeginCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRotateKeyBeginCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaRotateKeyBeginCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaRotateKeyBeginCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaRotateKeyBeginCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaRotateKeyBeginCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaRotateKeyBeginCmd) RotationId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaRotateKeyBeginCmd) RotationIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaRotateKeyBeginCmd) RotationIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaRotateKeyBeginCmd) MutateRotationId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaRotateKeyBeginCmd) ExpectedNewSpki(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaRotateKeyBeginCmd) ExpectedNewSpkiLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaRotateKeyBeginCmd) ExpectedNewSpkiBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaRotateKeyBeginCmd) MutateExpectedNewSpki(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaRotateKeyBeginCmd) AuditNewSpkiHash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaRotateKeyBeginCmd) AuditNewSpkiHashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaRotateKeyBeginCmd) AuditNewSpkiHashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaRotateKeyBeginCmd) MutateAuditNewSpkiHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaRotateKeyBeginCmd) StartedBy() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaRotateKeyBeginCmd) Capabilities() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaRotateKeyBeginCmd) MutateCapabilities(n uint32) bool {
	return rcv._tab.MutateUint32Slot(12, n)
}

func MetaRotateKeyBeginCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MetaRotateKeyBeginCmdAddRotationId(builder *flatbuffers.Builder, rotationId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(rotationId), 0)
}
func MetaRotateKeyBeginCmdStartRotationIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaRotateKeyBeginCmdAddExpectedNewSpki(builder *flatbuffers.Builder, expectedNewSpki flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(expectedNewSpki), 0)
}
func MetaRotateKeyBeginCmdStartExpectedNewSpkiVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaRotateKeyBeginCmdAddAuditNewSpkiHash(builder *flatbuffers.Builder, auditNewSpkiHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(auditNewSpkiHash), 0)
}
func MetaRotateKeyBeginCmdStartAuditNewSpkiHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaRotateKeyBeginCmdAddStartedBy(builder *flatbuffers.Builder, startedBy flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(startedBy), 0)
}
func MetaRotateKeyBeginCmdAddCapabilities(builder *flatbuffers.Builder, capabilities uint32) {
	builder.PrependUint32Slot(4, capabilities, 0)
}
func MetaRotateKeyBeginCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
