// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaCreateBucketCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaCreateBucketCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaCreateBucketCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaCreateBucketCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaCreateBucketCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaCreateBucketCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaCreateBucketCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaCreateBucketCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaCreateBucketCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaCreateBucketCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaCreateBucketCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaCreateBucketCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaCreateBucketCmd) GroupId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaCreateBucketCmd) BypassReserved() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *MetaCreateBucketCmd) MutateBypassReserved(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func MetaCreateBucketCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MetaCreateBucketCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func MetaCreateBucketCmdAddGroupId(builder *flatbuffers.Builder, groupId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(groupId), 0)
}
func MetaCreateBucketCmdAddBypassReserved(builder *flatbuffers.Builder, bypassReserved bool) {
	builder.PrependBoolSlot(2, bypassReserved, false)
}
func MetaCreateBucketCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
