// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaNodeEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaNodeEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaNodeEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaNodeEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaNodeEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaNodeEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaNodeEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaNodeEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaNodeEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaNodeEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaNodeEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaNodeEntry) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaNodeEntry) Address() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaNodeEntry) Role() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaNodeEntry) MutateRole(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func MetaNodeEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func MetaNodeEntryAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func MetaNodeEntryAddAddress(builder *flatbuffers.Builder, address flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(address), 0)
}
func MetaNodeEntryAddRole(builder *flatbuffers.Builder, role byte) {
	builder.PrependByteSlot(2, role, 0)
}
func MetaNodeEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
