// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaPolicyAttachToGroupDeleteCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaPolicyAttachToGroupDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPolicyAttachToGroupDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaPolicyAttachToGroupDeleteCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaPolicyAttachToGroupDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaPolicyAttachToGroupDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPolicyAttachToGroupDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaPolicyAttachToGroupDeleteCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaPolicyAttachToGroupDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaPolicyAttachToGroupDeleteCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaPolicyAttachToGroupDeleteCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaPolicyAttachToGroupDeleteCmd) Group() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaPolicyAttachToGroupDeleteCmd) Policy() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaPolicyAttachToGroupDeleteCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaPolicyAttachToGroupDeleteCmdAddGroup(builder *flatbuffers.Builder, group flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(group), 0)
}
func MetaPolicyAttachToGroupDeleteCmdAddPolicy(builder *flatbuffers.Builder, policy flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(policy), 0)
}
func MetaPolicyAttachToGroupDeleteCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
