// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaProtocolCredentialMarkStaleCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaProtocolCredentialMarkStaleCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialMarkStaleCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaProtocolCredentialMarkStaleCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaProtocolCredentialMarkStaleCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaProtocolCredentialMarkStaleCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialMarkStaleCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaProtocolCredentialMarkStaleCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaProtocolCredentialMarkStaleCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaProtocolCredentialMarkStaleCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaProtocolCredentialMarkStaleCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaProtocolCredentialMarkStaleCmd) RequestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialMarkStaleCmd) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialMarkStaleCmd) StaleAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaProtocolCredentialMarkStaleCmd) MutateStaleAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *MetaProtocolCredentialMarkStaleCmd) Reason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaProtocolCredentialMarkStaleCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MetaProtocolCredentialMarkStaleCmdAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requestId), 0)
}
func MetaProtocolCredentialMarkStaleCmdAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(id), 0)
}
func MetaProtocolCredentialMarkStaleCmdAddStaleAtUnixNanos(builder *flatbuffers.Builder, staleAtUnixNanos int64) {
	builder.PrependInt64Slot(2, staleAtUnixNanos, 0)
}
func MetaProtocolCredentialMarkStaleCmdAddReason(builder *flatbuffers.Builder, reason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(reason), 0)
}
func MetaProtocolCredentialMarkStaleCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
