// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaRevokePeerCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaRevokePeerCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRevokePeerCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaRevokePeerCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaRevokePeerCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaRevokePeerCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRevokePeerCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaRevokePeerCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaRevokePeerCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaRevokePeerCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaRevokePeerCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaRevokePeerCmd) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaRevokePeerCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaRevokePeerCmdAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func MetaRevokePeerCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
