// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaPromoteMemberCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaPromoteMemberCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPromoteMemberCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaPromoteMemberCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaPromoteMemberCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaPromoteMemberCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPromoteMemberCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaPromoteMemberCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaPromoteMemberCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaPromoteMemberCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaPromoteMemberCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaPromoteMemberCmd) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaPromoteMemberCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaPromoteMemberCmdAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func MetaPromoteMemberCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
