// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaIcebergCommitTableCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaIcebergCommitTableCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaIcebergCommitTableCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaIcebergCommitTableCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaIcebergCommitTableCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaIcebergCommitTableCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaIcebergCommitTableCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaIcebergCommitTableCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaIcebergCommitTableCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaIcebergCommitTableCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaIcebergCommitTableCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaIcebergCommitTableCmd) RequestId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaIcebergCommitTableCmd) Identifier(obj *IcebergIdentifier) *IcebergIdentifier {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(IcebergIdentifier)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MetaIcebergCommitTableCmd) ExpectedMetadataLocation() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaIcebergCommitTableCmd) NewMetadataLocation() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaIcebergCommitTableCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MetaIcebergCommitTableCmdAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(requestId), 0)
}
func MetaIcebergCommitTableCmdAddIdentifier(builder *flatbuffers.Builder, identifier flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(identifier), 0)
}
func MetaIcebergCommitTableCmdAddExpectedMetadataLocation(builder *flatbuffers.Builder, expectedMetadataLocation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(expectedMetadataLocation), 0)
}
func MetaIcebergCommitTableCmdAddNewMetadataLocation(builder *flatbuffers.Builder, newMetadataLocation flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(newMetadataLocation), 0)
}
func MetaIcebergCommitTableCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
