// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaKEKRotateCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaKEKRotateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaKEKRotateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaKEKRotateCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaKEKRotateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaKEKRotateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaKEKRotateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaKEKRotateCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaKEKRotateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaKEKRotateCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaKEKRotateCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaKEKRotateCmd) PayloadVersion() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *MetaKEKRotateCmd) MutatePayloadVersion(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *MetaKEKRotateCmd) NewVersion() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaKEKRotateCmd) MutateNewVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *MetaKEKRotateCmd) WrappedNewKek(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaKEKRotateCmd) WrappedNewKekLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaKEKRotateCmd) WrappedNewKekBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaKEKRotateCmd) MutateWrappedNewKek(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaKEKRotateCmd) WrapSetHash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaKEKRotateCmd) WrapSetHashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaKEKRotateCmd) WrapSetHashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaKEKRotateCmd) MutateWrapSetHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaKEKRotateCmd) RewrappedDeks(obj *RewrappedDEKEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *MetaKEKRotateCmd) RewrappedDeksLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaKEKRotateCmd) Confirm() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaKEKRotateCmd) Actor() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaKEKRotateCmd) RequestId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaKEKRotateCmd) RequestIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaKEKRotateCmd) RequestIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaKEKRotateCmd) MutateRequestId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaKEKRotateCmd) RequestedAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaKEKRotateCmd) MutateRequestedAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *MetaKEKRotateCmd) ClusterStateAtPropose(obj *ClusterStateAtPropose) *ClusterStateAtPropose {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ClusterStateAtPropose)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MetaKEKRotateCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func MetaKEKRotateCmdAddPayloadVersion(builder *flatbuffers.Builder, payloadVersion byte) {
	builder.PrependByteSlot(0, payloadVersion, 1)
}
func MetaKEKRotateCmdAddNewVersion(builder *flatbuffers.Builder, newVersion uint32) {
	builder.PrependUint32Slot(1, newVersion, 0)
}
func MetaKEKRotateCmdAddWrappedNewKek(builder *flatbuffers.Builder, wrappedNewKek flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(wrappedNewKek), 0)
}
func MetaKEKRotateCmdStartWrappedNewKekVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaKEKRotateCmdAddWrapSetHash(builder *flatbuffers.Builder, wrapSetHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(wrapSetHash), 0)
}
func MetaKEKRotateCmdStartWrapSetHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaKEKRotateCmdAddRewrappedDeks(builder *flatbuffers.Builder, rewrappedDeks flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(rewrappedDeks), 0)
}
func MetaKEKRotateCmdStartRewrappedDeksVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MetaKEKRotateCmdAddConfirm(builder *flatbuffers.Builder, confirm flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(confirm), 0)
}
func MetaKEKRotateCmdAddActor(builder *flatbuffers.Builder, actor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(actor), 0)
}
func MetaKEKRotateCmdAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(requestId), 0)
}
func MetaKEKRotateCmdStartRequestIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaKEKRotateCmdAddRequestedAtUnixNanos(builder *flatbuffers.Builder, requestedAtUnixNanos int64) {
	builder.PrependInt64Slot(8, requestedAtUnixNanos, 0)
}
func MetaKEKRotateCmdAddClusterStateAtPropose(builder *flatbuffers.Builder, clusterStateAtPropose flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(clusterStateAtPropose), 0)
}
func MetaKEKRotateCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
