// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaKEKRetireCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaKEKRetireCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaKEKRetireCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaKEKRetireCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaKEKRetireCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaKEKRetireCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaKEKRetireCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaKEKRetireCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaKEKRetireCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaKEKRetireCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaKEKRetireCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaKEKRetireCmd) PayloadVersion() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *MetaKEKRetireCmd) MutatePayloadVersion(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *MetaKEKRetireCmd) Version() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaKEKRetireCmd) MutateVersion(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *MetaKEKRetireCmd) Confirm() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaKEKRetireCmd) Actor() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaKEKRetireCmd) RequestId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaKEKRetireCmd) RequestIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaKEKRetireCmd) RequestIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaKEKRetireCmd) MutateRequestId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaKEKRetireCmd) RequestedAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaKEKRetireCmd) MutateRequestedAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *MetaKEKRetireCmd) ClusterStateAtPropose(obj *ClusterStateAtPropose) *ClusterStateAtPropose {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ClusterStateAtPropose)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MetaKEKRetireCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func MetaKEKRetireCmdAddPayloadVersion(builder *flatbuffers.Builder, payloadVersion byte) {
	builder.PrependByteSlot(0, payloadVersion, 1)
}
func MetaKEKRetireCmdAddVersion(builder *flatbuffers.Builder, version uint32) {
	builder.PrependUint32Slot(1, version, 0)
}
func MetaKEKRetireCmdAddConfirm(builder *flatbuffers.Builder, confirm flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(confirm), 0)
}
func MetaKEKRetireCmdAddActor(builder *flatbuffers.Builder, actor flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(actor), 0)
}
func MetaKEKRetireCmdAddRequestId(builder *flatbuffers.Builder, requestId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(requestId), 0)
}
func MetaKEKRetireCmdStartRequestIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaKEKRetireCmdAddRequestedAtUnixNanos(builder *flatbuffers.Builder, requestedAtUnixNanos int64) {
	builder.PrependInt64Slot(5, requestedAtUnixNanos, 0)
}
func MetaKEKRetireCmdAddClusterStateAtPropose(builder *flatbuffers.Builder, clusterStateAtPropose flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(clusterStateAtPropose), 0)
}
func MetaKEKRetireCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
