// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaDEKReplicatedRotateCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaDEKReplicatedRotateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaDEKReplicatedRotateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaDEKReplicatedRotateCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaDEKReplicatedRotateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaDEKReplicatedRotateCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaDEKReplicatedRotateCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaDEKReplicatedRotateCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaDEKReplicatedRotateCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaDEKReplicatedRotateCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaDEKReplicatedRotateCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaDEKReplicatedRotateCmd) Gen() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaDEKReplicatedRotateCmd) MutateGen(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func (rcv *MetaDEKReplicatedRotateCmd) WrappedDek(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaDEKReplicatedRotateCmd) WrappedDekLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaDEKReplicatedRotateCmd) WrappedDekBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaDEKReplicatedRotateCmd) MutateWrappedDek(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaDEKReplicatedRotateCmd) ExpectedActiveGen() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaDEKReplicatedRotateCmd) MutateExpectedActiveGen(n uint32) bool {
	return rcv._tab.MutateUint32Slot(8, n)
}

func (rcv *MetaDEKReplicatedRotateCmd) ActiveKekVer() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaDEKReplicatedRotateCmd) MutateActiveKekVer(n uint32) bool {
	return rcv._tab.MutateUint32Slot(10, n)
}

func MetaDEKReplicatedRotateCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MetaDEKReplicatedRotateCmdAddGen(builder *flatbuffers.Builder, gen uint32) {
	builder.PrependUint32Slot(0, gen, 0)
}
func MetaDEKReplicatedRotateCmdAddWrappedDek(builder *flatbuffers.Builder, wrappedDek flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(wrappedDek), 0)
}
func MetaDEKReplicatedRotateCmdStartWrappedDekVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaDEKReplicatedRotateCmdAddExpectedActiveGen(builder *flatbuffers.Builder, expectedActiveGen uint32) {
	builder.PrependUint32Slot(2, expectedActiveGen, 0)
}
func MetaDEKReplicatedRotateCmdAddActiveKekVer(builder *flatbuffers.Builder, activeKekVer uint32) {
	builder.PrependUint32Slot(3, activeKekVer, 0)
}
func MetaDEKReplicatedRotateCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
