// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaRemoveNodeCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaRemoveNodeCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRemoveNodeCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaRemoveNodeCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaRemoveNodeCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaRemoveNodeCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaRemoveNodeCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaRemoveNodeCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaRemoveNodeCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaRemoveNodeCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaRemoveNodeCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaRemoveNodeCmd) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaRemoveNodeCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaRemoveNodeCmdAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func MetaRemoveNodeCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
