// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaCatalogReadRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaCatalogReadRequest(buf []byte, offset flatbuffers.UOffsetT) *MetaCatalogReadRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaCatalogReadRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaCatalogReadRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaCatalogReadRequest(buf []byte, offset flatbuffers.UOffsetT) *MetaCatalogReadRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaCatalogReadRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaCatalogReadRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaCatalogReadRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaCatalogReadRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaCatalogReadRequest) Op() CatalogReadOp {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return CatalogReadOp(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *MetaCatalogReadRequest) MutateOp(n CatalogReadOp) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *MetaCatalogReadRequest) Namespace(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *MetaCatalogReadRequest) NamespaceLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaCatalogReadRequest) Identifier(obj *CatalogIdentifier) *CatalogIdentifier {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(CatalogIdentifier)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *MetaCatalogReadRequest) Warehouse() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaCatalogReadRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MetaCatalogReadRequestAddOp(builder *flatbuffers.Builder, op CatalogReadOp) {
	builder.PrependInt8Slot(0, int8(op), 0)
}
func MetaCatalogReadRequestAddNamespace(builder *flatbuffers.Builder, namespace flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(namespace), 0)
}
func MetaCatalogReadRequestStartNamespaceVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func MetaCatalogReadRequestAddIdentifier(builder *flatbuffers.Builder, identifier flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(identifier), 0)
}
func MetaCatalogReadRequestAddWarehouse(builder *flatbuffers.Builder, warehouse flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(warehouse), 0)
}
func MetaCatalogReadRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
