// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaIAMBucketPolicyEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaIAMBucketPolicyEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaIAMBucketPolicyEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaIAMBucketPolicyEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaIAMBucketPolicyEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaIAMBucketPolicyEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaIAMBucketPolicyEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaIAMBucketPolicyEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaIAMBucketPolicyEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaIAMBucketPolicyEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaIAMBucketPolicyEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaIAMBucketPolicyEntry) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaIAMBucketPolicyEntry) DocJson(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaIAMBucketPolicyEntry) DocJsonLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaIAMBucketPolicyEntry) DocJsonBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaIAMBucketPolicyEntry) MutateDocJson(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func MetaIAMBucketPolicyEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaIAMBucketPolicyEntryAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func MetaIAMBucketPolicyEntryAddDocJson(builder *flatbuffers.Builder, docJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(docJson), 0)
}
func MetaIAMBucketPolicyEntryStartDocJsonVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaIAMBucketPolicyEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
