// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaProtocolCredentialEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaProtocolCredentialEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaProtocolCredentialEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaProtocolCredentialEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaProtocolCredentialEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaProtocolCredentialEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaProtocolCredentialEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaProtocolCredentialEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaProtocolCredentialEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaProtocolCredentialEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaProtocolCredentialEntry) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialEntry) SaId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialEntry) Protocol() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialEntry) Resource() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialEntry) Mode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialEntry) SecretHash(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *MetaProtocolCredentialEntry) SecretHashLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *MetaProtocolCredentialEntry) SecretHashBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialEntry) MutateSecretHash(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *MetaProtocolCredentialEntry) SecretHint() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialEntry) CreatedAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaProtocolCredentialEntry) MutateCreatedAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *MetaProtocolCredentialEntry) CreatedBy() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaProtocolCredentialEntry) ExpiresAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaProtocolCredentialEntry) MutateExpiresAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(22, n)
}

func (rcv *MetaProtocolCredentialEntry) RevokedAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaProtocolCredentialEntry) MutateRevokedAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(24, n)
}

func (rcv *MetaProtocolCredentialEntry) LastUsedAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaProtocolCredentialEntry) MutateLastUsedAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(26, n)
}

func (rcv *MetaProtocolCredentialEntry) Generation() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaProtocolCredentialEntry) MutateGeneration(n uint64) bool {
	return rcv._tab.MutateUint64Slot(28, n)
}

func (rcv *MetaProtocolCredentialEntry) StaleAtUnixNanos() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaProtocolCredentialEntry) MutateStaleAtUnixNanos(n int64) bool {
	return rcv._tab.MutateInt64Slot(30, n)
}

func (rcv *MetaProtocolCredentialEntry) StaleReason() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaProtocolCredentialEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func MetaProtocolCredentialEntryAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func MetaProtocolCredentialEntryAddSaId(builder *flatbuffers.Builder, saId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(saId), 0)
}
func MetaProtocolCredentialEntryAddProtocol(builder *flatbuffers.Builder, protocol flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(protocol), 0)
}
func MetaProtocolCredentialEntryAddResource(builder *flatbuffers.Builder, resource flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(resource), 0)
}
func MetaProtocolCredentialEntryAddMode(builder *flatbuffers.Builder, mode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(mode), 0)
}
func MetaProtocolCredentialEntryAddSecretHash(builder *flatbuffers.Builder, secretHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(secretHash), 0)
}
func MetaProtocolCredentialEntryStartSecretHashVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func MetaProtocolCredentialEntryAddSecretHint(builder *flatbuffers.Builder, secretHint flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(secretHint), 0)
}
func MetaProtocolCredentialEntryAddCreatedAtUnixNanos(builder *flatbuffers.Builder, createdAtUnixNanos int64) {
	builder.PrependInt64Slot(7, createdAtUnixNanos, 0)
}
func MetaProtocolCredentialEntryAddCreatedBy(builder *flatbuffers.Builder, createdBy flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(createdBy), 0)
}
func MetaProtocolCredentialEntryAddExpiresAtUnixNanos(builder *flatbuffers.Builder, expiresAtUnixNanos int64) {
	builder.PrependInt64Slot(9, expiresAtUnixNanos, 0)
}
func MetaProtocolCredentialEntryAddRevokedAtUnixNanos(builder *flatbuffers.Builder, revokedAtUnixNanos int64) {
	builder.PrependInt64Slot(10, revokedAtUnixNanos, 0)
}
func MetaProtocolCredentialEntryAddLastUsedAtUnixNanos(builder *flatbuffers.Builder, lastUsedAtUnixNanos int64) {
	builder.PrependInt64Slot(11, lastUsedAtUnixNanos, 0)
}
func MetaProtocolCredentialEntryAddGeneration(builder *flatbuffers.Builder, generation uint64) {
	builder.PrependUint64Slot(12, generation, 0)
}
func MetaProtocolCredentialEntryAddStaleAtUnixNanos(builder *flatbuffers.Builder, staleAtUnixNanos int64) {
	builder.PrependInt64Slot(13, staleAtUnixNanos, 0)
}
func MetaProtocolCredentialEntryAddStaleReason(builder *flatbuffers.Builder, staleReason flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(14, flatbuffers.UOffsetT(staleReason), 0)
}
func MetaProtocolCredentialEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
