// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaGroupMemberDeleteCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaGroupMemberDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaGroupMemberDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaGroupMemberDeleteCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaGroupMemberDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaGroupMemberDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaGroupMemberDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaGroupMemberDeleteCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaGroupMemberDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaGroupMemberDeleteCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaGroupMemberDeleteCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaGroupMemberDeleteCmd) Group() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaGroupMemberDeleteCmd) SaId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaGroupMemberDeleteCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaGroupMemberDeleteCmdAddGroup(builder *flatbuffers.Builder, group flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(group), 0)
}
func MetaGroupMemberDeleteCmdAddSaId(builder *flatbuffers.Builder, saId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(saId), 0)
}
func MetaGroupMemberDeleteCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
