// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaMountSAEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaMountSAEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaMountSAEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaMountSAEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaMountSAEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaMountSAEntry(buf []byte, offset flatbuffers.UOffsetT) *MetaMountSAEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaMountSAEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaMountSAEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaMountSAEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaMountSAEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaMountSAEntry) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaMountSAEntry) NumericUid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaMountSAEntry) MutateNumericUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *MetaMountSAEntry) CreatedAt() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MetaMountSAEntry) MutateCreatedAt(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *MetaMountSAEntry) CreatedBy() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaMountSAEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MetaMountSAEntryAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func MetaMountSAEntryAddNumericUid(builder *flatbuffers.Builder, numericUid uint32) {
	builder.PrependUint32Slot(1, numericUid, 0)
}
func MetaMountSAEntryAddCreatedAt(builder *flatbuffers.Builder, createdAt int64) {
	builder.PrependInt64Slot(2, createdAt, 0)
}
func MetaMountSAEntryAddCreatedBy(builder *flatbuffers.Builder, createdBy flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(createdBy), 0)
}
func MetaMountSAEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
