// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaBucketPolicyDeleteCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaBucketPolicyDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaBucketPolicyDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaBucketPolicyDeleteCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaBucketPolicyDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaBucketPolicyDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaBucketPolicyDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaBucketPolicyDeleteCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaBucketPolicyDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaBucketPolicyDeleteCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaBucketPolicyDeleteCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaBucketPolicyDeleteCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaBucketPolicyDeleteCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MetaBucketPolicyDeleteCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func MetaBucketPolicyDeleteCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
