// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MetaPolicyAttachToSADeleteCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMetaPolicyAttachToSADeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPolicyAttachToSADeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MetaPolicyAttachToSADeleteCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMetaPolicyAttachToSADeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMetaPolicyAttachToSADeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *MetaPolicyAttachToSADeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MetaPolicyAttachToSADeleteCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMetaPolicyAttachToSADeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MetaPolicyAttachToSADeleteCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MetaPolicyAttachToSADeleteCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MetaPolicyAttachToSADeleteCmd) SaId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MetaPolicyAttachToSADeleteCmd) Policy() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MetaPolicyAttachToSADeleteCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MetaPolicyAttachToSADeleteCmdAddSaId(builder *flatbuffers.Builder, saId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(saId), 0)
}
func MetaPolicyAttachToSADeleteCmdAddPolicy(builder *flatbuffers.Builder, policy flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(policy), 0)
}
func MetaPolicyAttachToSADeleteCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
