// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MigrationDoneCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsMigrationDoneCmd(buf []byte, offset flatbuffers.UOffsetT) *MigrationDoneCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MigrationDoneCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishMigrationDoneCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMigrationDoneCmd(buf []byte, offset flatbuffers.UOffsetT) *MigrationDoneCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MigrationDoneCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMigrationDoneCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MigrationDoneCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MigrationDoneCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MigrationDoneCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MigrationDoneCmd) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MigrationDoneCmd) VersionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MigrationDoneCmd) SrcNode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MigrationDoneCmd) DstNode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MigrationDoneCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func MigrationDoneCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func MigrationDoneCmdAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func MigrationDoneCmdAddVersionId(builder *flatbuffers.Builder, versionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(versionId), 0)
}
func MigrationDoneCmdAddSrcNode(builder *flatbuffers.Builder, srcNode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(srcNode), 0)
}
func MigrationDoneCmdAddDstNode(builder *flatbuffers.Builder, dstNode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(dstNode), 0)
}
func MigrationDoneCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
