// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MountSAAttachPolicyPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsMountSAAttachPolicyPayload(buf []byte, offset flatbuffers.UOffsetT) *MountSAAttachPolicyPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MountSAAttachPolicyPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishMountSAAttachPolicyPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMountSAAttachPolicyPayload(buf []byte, offset flatbuffers.UOffsetT) *MountSAAttachPolicyPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MountSAAttachPolicyPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMountSAAttachPolicyPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MountSAAttachPolicyPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MountSAAttachPolicyPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MountSAAttachPolicyPayload) MountSa() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MountSAAttachPolicyPayload) Policy() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MountSAAttachPolicyPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MountSAAttachPolicyPayloadAddMountSa(builder *flatbuffers.Builder, mountSa flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(mountSa), 0)
}
func MountSAAttachPolicyPayloadAddPolicy(builder *flatbuffers.Builder, policy flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(policy), 0)
}
func MountSAAttachPolicyPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
