// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MountSADetachPolicyPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsMountSADetachPolicyPayload(buf []byte, offset flatbuffers.UOffsetT) *MountSADetachPolicyPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MountSADetachPolicyPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishMountSADetachPolicyPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMountSADetachPolicyPayload(buf []byte, offset flatbuffers.UOffsetT) *MountSADetachPolicyPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MountSADetachPolicyPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMountSADetachPolicyPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MountSADetachPolicyPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MountSADetachPolicyPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MountSADetachPolicyPayload) MountSa() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MountSADetachPolicyPayload) Policy() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MountSADetachPolicyPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MountSADetachPolicyPayloadAddMountSa(builder *flatbuffers.Builder, mountSa flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(mountSa), 0)
}
func MountSADetachPolicyPayloadAddPolicy(builder *flatbuffers.Builder, policy flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(policy), 0)
}
func MountSADetachPolicyPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
