// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MountSACreatePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsMountSACreatePayload(buf []byte, offset flatbuffers.UOffsetT) *MountSACreatePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MountSACreatePayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishMountSACreatePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMountSACreatePayload(buf []byte, offset flatbuffers.UOffsetT) *MountSACreatePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MountSACreatePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMountSACreatePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MountSACreatePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MountSACreatePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MountSACreatePayload) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MountSACreatePayload) NumericUid() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MountSACreatePayload) MutateNumericUid(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func (rcv *MountSACreatePayload) CreatedAt() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *MountSACreatePayload) MutateCreatedAt(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *MountSACreatePayload) CreatedBy() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MountSACreatePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func MountSACreatePayloadAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func MountSACreatePayloadAddNumericUid(builder *flatbuffers.Builder, numericUid uint32) {
	builder.PrependUint32Slot(1, numericUid, 0)
}
func MountSACreatePayloadAddCreatedAt(builder *flatbuffers.Builder, createdAt int64) {
	builder.PrependInt64Slot(2, createdAt, 0)
}
func MountSACreatePayloadAddCreatedBy(builder *flatbuffers.Builder, createdBy flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(createdBy), 0)
}
func MountSACreatePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
