// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MultipartMeta struct {
	_tab flatbuffers.Table
}

func GetRootAsMultipartMeta(buf []byte, offset flatbuffers.UOffsetT) *MultipartMeta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MultipartMeta{}
	x.Init(buf, n+offset)
	return x
}

func FinishMultipartMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsMultipartMeta(buf []byte, offset flatbuffers.UOffsetT) *MultipartMeta {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MultipartMeta{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedMultipartMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *MultipartMeta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MultipartMeta) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MultipartMeta) ContentType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MultipartMetaStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MultipartMetaAddContentType(builder *flatbuffers.Builder, contentType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(contentType), 0)
}
func MultipartMetaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
