// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NfsExportDeleteCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsNfsExportDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *NfsExportDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NfsExportDeleteCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishNfsExportDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNfsExportDeleteCmd(buf []byte, offset flatbuffers.UOffsetT) *NfsExportDeleteCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NfsExportDeleteCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNfsExportDeleteCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NfsExportDeleteCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NfsExportDeleteCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NfsExportDeleteCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NfsExportDeleteCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NfsExportDeleteCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func NfsExportDeleteCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
