// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NfsExportBucketDeleteCascadeCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsNfsExportBucketDeleteCascadeCmd(buf []byte, offset flatbuffers.UOffsetT) *NfsExportBucketDeleteCascadeCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NfsExportBucketDeleteCascadeCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishNfsExportBucketDeleteCascadeCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsNfsExportBucketDeleteCascadeCmd(buf []byte, offset flatbuffers.UOffsetT) *NfsExportBucketDeleteCascadeCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NfsExportBucketDeleteCascadeCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedNfsExportBucketDeleteCascadeCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *NfsExportBucketDeleteCascadeCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NfsExportBucketDeleteCascadeCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NfsExportBucketDeleteCascadeCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *NfsExportBucketDeleteCascadeCmd) Force() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *NfsExportBucketDeleteCascadeCmd) MutateForce(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func NfsExportBucketDeleteCascadeCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func NfsExportBucketDeleteCascadeCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func NfsExportBucketDeleteCascadeCmdAddForce(builder *flatbuffers.Builder, force bool) {
	builder.PrependBoolSlot(1, force, false)
}
func NfsExportBucketDeleteCascadeCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
