// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ObjectMeta struct {
	_tab flatbuffers.Table
}

func GetRootAsObjectMeta(buf []byte, offset flatbuffers.UOffsetT) *ObjectMeta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ObjectMeta{}
	x.Init(buf, n+offset)
	return x
}

func FinishObjectMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsObjectMeta(buf []byte, offset flatbuffers.UOffsetT) *ObjectMeta {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ObjectMeta{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedObjectMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ObjectMeta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ObjectMeta) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ObjectMeta) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ObjectMeta) Size() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ObjectMeta) MutateSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *ObjectMeta) ContentType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ObjectMeta) Etag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ObjectMeta) LastModified() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ObjectMeta) MutateLastModified(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *ObjectMeta) Acl() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ObjectMeta) MutateAcl(n byte) bool {
	return rcv._tab.MutateByteSlot(14, n)
}

func (rcv *ObjectMeta) RingVersion() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ObjectMeta) MutateRingVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(16, n)
}

func (rcv *ObjectMeta) EcData() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ObjectMeta) MutateEcData(n byte) bool {
	return rcv._tab.MutateByteSlot(18, n)
}

func (rcv *ObjectMeta) EcParity() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ObjectMeta) MutateEcParity(n byte) bool {
	return rcv._tab.MutateByteSlot(20, n)
}

func (rcv *ObjectMeta) NodeIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *ObjectMeta) NodeIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ObjectMetaStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func ObjectMetaAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func ObjectMetaAddSize(builder *flatbuffers.Builder, size int64) {
	builder.PrependInt64Slot(1, size, 0)
}
func ObjectMetaAddContentType(builder *flatbuffers.Builder, contentType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(contentType), 0)
}
func ObjectMetaAddEtag(builder *flatbuffers.Builder, etag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(etag), 0)
}
func ObjectMetaAddLastModified(builder *flatbuffers.Builder, lastModified int64) {
	builder.PrependInt64Slot(4, lastModified, 0)
}
func ObjectMetaAddAcl(builder *flatbuffers.Builder, acl byte) {
	builder.PrependByteSlot(5, acl, 0)
}
func ObjectMetaAddRingVersion(builder *flatbuffers.Builder, ringVersion uint64) {
	builder.PrependUint64Slot(6, ringVersion, 0)
}
func ObjectMetaAddEcData(builder *flatbuffers.Builder, ecData byte) {
	builder.PrependByteSlot(7, ecData, 0)
}
func ObjectMetaAddEcParity(builder *flatbuffers.Builder, ecParity byte) {
	builder.PrependByteSlot(8, ecParity, 0)
}
func ObjectMetaAddNodeIds(builder *flatbuffers.Builder, nodeIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(nodeIds), 0)
}
func ObjectMetaStartNodeIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ObjectMetaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
