// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PutObjectMetaCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsPutObjectMetaCmd(buf []byte, offset flatbuffers.UOffsetT) *PutObjectMetaCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PutObjectMetaCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishPutObjectMetaCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPutObjectMetaCmd(buf []byte, offset flatbuffers.UOffsetT) *PutObjectMetaCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PutObjectMetaCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPutObjectMetaCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PutObjectMetaCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PutObjectMetaCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PutObjectMetaCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PutObjectMetaCmd) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PutObjectMetaCmd) Size() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PutObjectMetaCmd) MutateSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *PutObjectMetaCmd) ContentType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PutObjectMetaCmd) Etag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PutObjectMetaCmd) ModTime() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PutObjectMetaCmd) MutateModTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *PutObjectMetaCmd) VersionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PutObjectMetaCmd) RingVersion() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PutObjectMetaCmd) MutateRingVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(18, n)
}

func (rcv *PutObjectMetaCmd) EcData() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PutObjectMetaCmd) MutateEcData(n byte) bool {
	return rcv._tab.MutateByteSlot(20, n)
}

func (rcv *PutObjectMetaCmd) EcParity() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PutObjectMetaCmd) MutateEcParity(n byte) bool {
	return rcv._tab.MutateByteSlot(22, n)
}

func (rcv *PutObjectMetaCmd) NodeIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *PutObjectMetaCmd) NodeIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PutObjectMetaCmd) PreserveLatest() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PutObjectMetaCmd) MutatePreserveLatest(n bool) bool {
	return rcv._tab.MutateBoolSlot(26, n)
}

func (rcv *PutObjectMetaCmd) IsDeleteMarker() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PutObjectMetaCmd) MutateIsDeleteMarker(n bool) bool {
	return rcv._tab.MutateBoolSlot(28, n)
}

func PutObjectMetaCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func PutObjectMetaCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func PutObjectMetaCmdAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func PutObjectMetaCmdAddSize(builder *flatbuffers.Builder, size int64) {
	builder.PrependInt64Slot(2, size, 0)
}
func PutObjectMetaCmdAddContentType(builder *flatbuffers.Builder, contentType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(contentType), 0)
}
func PutObjectMetaCmdAddEtag(builder *flatbuffers.Builder, etag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(etag), 0)
}
func PutObjectMetaCmdAddModTime(builder *flatbuffers.Builder, modTime int64) {
	builder.PrependInt64Slot(5, modTime, 0)
}
func PutObjectMetaCmdAddVersionId(builder *flatbuffers.Builder, versionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(versionId), 0)
}
func PutObjectMetaCmdAddRingVersion(builder *flatbuffers.Builder, ringVersion uint64) {
	builder.PrependUint64Slot(7, ringVersion, 0)
}
func PutObjectMetaCmdAddEcData(builder *flatbuffers.Builder, ecData byte) {
	builder.PrependByteSlot(8, ecData, 0)
}
func PutObjectMetaCmdAddEcParity(builder *flatbuffers.Builder, ecParity byte) {
	builder.PrependByteSlot(9, ecParity, 0)
}
func PutObjectMetaCmdAddNodeIds(builder *flatbuffers.Builder, nodeIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(nodeIds), 0)
}
func PutObjectMetaCmdAddPreserveLatest(builder *flatbuffers.Builder, preserveLatest bool) {
	builder.PrependBoolSlot(11, preserveLatest, false)
}
func PutObjectMetaCmdAddIsDeleteMarker(builder *flatbuffers.Builder, isDeleteMarker bool) {
	builder.PrependBoolSlot(12, isDeleteMarker, false)
}
func PutObjectMetaCmdStartNodeIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PutObjectMetaCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
