// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PutShardPlacementCmd struct {
	_tab flatbuffers.Table
}

func GetRootAsPutShardPlacementCmd(buf []byte, offset flatbuffers.UOffsetT) *PutShardPlacementCmd {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PutShardPlacementCmd{}
	x.Init(buf, n+offset)
	return x
}

func FinishPutShardPlacementCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPutShardPlacementCmd(buf []byte, offset flatbuffers.UOffsetT) *PutShardPlacementCmd {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PutShardPlacementCmd{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPutShardPlacementCmdBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PutShardPlacementCmd) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PutShardPlacementCmd) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PutShardPlacementCmd) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PutShardPlacementCmd) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PutShardPlacementCmd) NodeIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *PutShardPlacementCmd) NodeIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PutShardPlacementCmd) K() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PutShardPlacementCmd) MutateK(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *PutShardPlacementCmd) M() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PutShardPlacementCmd) MutateM(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func PutShardPlacementCmdStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func PutShardPlacementCmdAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func PutShardPlacementCmdAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func PutShardPlacementCmdAddNodeIds(builder *flatbuffers.Builder, nodeIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(nodeIds), 0)
}
func PutShardPlacementCmdStartNodeIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func PutShardPlacementCmdAddK(builder *flatbuffers.Builder, k int32) {
	builder.PrependInt32Slot(3, k, 0)
}
func PutShardPlacementCmdAddM(builder *flatbuffers.Builder, m int32) {
	builder.PrependInt32Slot(4, m, 0)
}
func PutShardPlacementCmdEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
