// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RebalancePlan struct {
	_tab flatbuffers.Table
}

func GetRootAsRebalancePlan(buf []byte, offset flatbuffers.UOffsetT) *RebalancePlan {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RebalancePlan{}
	x.Init(buf, n+offset)
	return x
}

func FinishRebalancePlanBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRebalancePlan(buf []byte, offset flatbuffers.UOffsetT) *RebalancePlan {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RebalancePlan{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRebalancePlanBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RebalancePlan) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RebalancePlan) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RebalancePlan) PlanId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RebalancePlan) GroupId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RebalancePlan) FromNode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RebalancePlan) ToNode() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RebalancePlan) CreatedAtUnix() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RebalancePlan) MutateCreatedAtUnix(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func RebalancePlanStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func RebalancePlanAddPlanId(builder *flatbuffers.Builder, planId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(planId), 0)
}
func RebalancePlanAddGroupId(builder *flatbuffers.Builder, groupId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(groupId), 0)
}
func RebalancePlanAddFromNode(builder *flatbuffers.Builder, fromNode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(fromNode), 0)
}
func RebalancePlanAddToNode(builder *flatbuffers.Builder, toNode flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(toNode), 0)
}
func RebalancePlanAddCreatedAtUnix(builder *flatbuffers.Builder, createdAtUnix int64) {
	builder.PrependInt64Slot(4, createdAtUnix, 0)
}
func RebalancePlanEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
