// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReceiptQueryMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsReceiptQueryMsg(buf []byte, offset flatbuffers.UOffsetT) *ReceiptQueryMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReceiptQueryMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishReceiptQueryMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsReceiptQueryMsg(buf []byte, offset flatbuffers.UOffsetT) *ReceiptQueryMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReceiptQueryMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedReceiptQueryMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ReceiptQueryMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReceiptQueryMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReceiptQueryMsg) ReceiptId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ReceiptQueryMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ReceiptQueryMsgAddReceiptId(builder *flatbuffers.Builder, receiptId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(receiptId), 0)
}
func ReceiptQueryMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
