// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReceiptQueryResponseMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsReceiptQueryResponseMsg(buf []byte, offset flatbuffers.UOffsetT) *ReceiptQueryResponseMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReceiptQueryResponseMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishReceiptQueryResponseMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsReceiptQueryResponseMsg(buf []byte, offset flatbuffers.UOffsetT) *ReceiptQueryResponseMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReceiptQueryResponseMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedReceiptQueryResponseMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ReceiptQueryResponseMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReceiptQueryResponseMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReceiptQueryResponseMsg) Found() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ReceiptQueryResponseMsg) MutateFound(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *ReceiptQueryResponseMsg) ReceiptJson(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ReceiptQueryResponseMsg) ReceiptJsonLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ReceiptQueryResponseMsg) ReceiptJsonBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ReceiptQueryResponseMsg) MutateReceiptJson(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func ReceiptQueryResponseMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ReceiptQueryResponseMsgAddFound(builder *flatbuffers.Builder, found bool) {
	builder.PrependBoolSlot(0, found, false)
}
func ReceiptQueryResponseMsgAddReceiptJson(builder *flatbuffers.Builder, receiptJson flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(receiptJson), 0)
}
func ReceiptQueryResponseMsgStartReceiptJsonVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ReceiptQueryResponseMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
