// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReceiptGossipMsg struct {
	_tab flatbuffers.Table
}

func GetRootAsReceiptGossipMsg(buf []byte, offset flatbuffers.UOffsetT) *ReceiptGossipMsg {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReceiptGossipMsg{}
	x.Init(buf, n+offset)
	return x
}

func FinishReceiptGossipMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsReceiptGossipMsg(buf []byte, offset flatbuffers.UOffsetT) *ReceiptGossipMsg {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ReceiptGossipMsg{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedReceiptGossipMsgBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ReceiptGossipMsg) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReceiptGossipMsg) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReceiptGossipMsg) NodeId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ReceiptGossipMsg) ReceiptIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *ReceiptGossipMsg) ReceiptIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ReceiptGossipMsgStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ReceiptGossipMsgAddNodeId(builder *flatbuffers.Builder, nodeId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nodeId), 0)
}
func ReceiptGossipMsgAddReceiptIds(builder *flatbuffers.Builder, receiptIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(receiptIds), 0)
}
func ReceiptGossipMsgStartReceiptIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ReceiptGossipMsgEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
