// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package clusterpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SegmentMetaEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsSegmentMetaEntry(buf []byte, offset flatbuffers.UOffsetT) *SegmentMetaEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SegmentMetaEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishSegmentMetaEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSegmentMetaEntry(buf []byte, offset flatbuffers.UOffsetT) *SegmentMetaEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SegmentMetaEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSegmentMetaEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SegmentMetaEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SegmentMetaEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SegmentMetaEntry) BlobId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SegmentMetaEntry) Size() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentMetaEntry) MutateSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *SegmentMetaEntry) Checksum(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *SegmentMetaEntry) ChecksumLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SegmentMetaEntry) ChecksumBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SegmentMetaEntry) MutateChecksum(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *SegmentMetaEntry) PlacementGroupId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SegmentMetaEntry) ShardSize() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentMetaEntry) MutateShardSize(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func (rcv *SegmentMetaEntry) SegmentIdx() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentMetaEntry) MutateSegmentIdx(n int32) bool {
	return rcv._tab.MutateInt32Slot(14, n)
}

func (rcv *SegmentMetaEntry) NodeIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *SegmentMetaEntry) NodeIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *SegmentMetaEntry) EcData() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentMetaEntry) MutateEcData(n byte) bool {
	return rcv._tab.MutateByteSlot(18, n)
}

func (rcv *SegmentMetaEntry) EcParity() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentMetaEntry) MutateEcParity(n byte) bool {
	return rcv._tab.MutateByteSlot(20, n)
}

func (rcv *SegmentMetaEntry) RingVersion() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentMetaEntry) MutateRingVersion(n uint64) bool {
	return rcv._tab.MutateUint64Slot(22, n)
}

func SegmentMetaEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(10)
}
func SegmentMetaEntryAddBlobId(builder *flatbuffers.Builder, blobId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(blobId), 0)
}
func SegmentMetaEntryAddSize(builder *flatbuffers.Builder, size int64) {
	builder.PrependInt64Slot(1, size, 0)
}
func SegmentMetaEntryAddChecksum(builder *flatbuffers.Builder, checksum flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(checksum), 0)
}
func SegmentMetaEntryStartChecksumVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func SegmentMetaEntryAddPlacementGroupId(builder *flatbuffers.Builder, placementGroupId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(placementGroupId), 0)
}
func SegmentMetaEntryAddShardSize(builder *flatbuffers.Builder, shardSize int32) {
	builder.PrependInt32Slot(4, shardSize, 0)
}
func SegmentMetaEntryAddSegmentIdx(builder *flatbuffers.Builder, segmentIdx int32) {
	builder.PrependInt32Slot(5, segmentIdx, 0)
}
func SegmentMetaEntryAddNodeIds(builder *flatbuffers.Builder, nodeIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(nodeIds), 0)
}
func SegmentMetaEntryStartNodeIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SegmentMetaEntryAddEcData(builder *flatbuffers.Builder, ecData byte) {
	builder.PrependByteSlot(7, ecData, 0)
}
func SegmentMetaEntryAddEcParity(builder *flatbuffers.Builder, ecParity byte) {
	builder.PrependByteSlot(8, ecParity, 0)
}
func SegmentMetaEntryAddRingVersion(builder *flatbuffers.Builder, ringVersion uint64) {
	builder.PrependUint64Slot(9, ringVersion, 0)
}
func SegmentMetaEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
