// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package iampb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AuthEnablePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthEnablePayload(buf []byte, offset flatbuffers.UOffsetT) *AuthEnablePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AuthEnablePayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishAuthEnablePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAuthEnablePayload(buf []byte, offset flatbuffers.UOffsetT) *AuthEnablePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AuthEnablePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAuthEnablePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AuthEnablePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AuthEnablePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func AuthEnablePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AuthEnablePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
