// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package iampb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type BucketUpstreamDeletePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsBucketUpstreamDeletePayload(buf []byte, offset flatbuffers.UOffsetT) *BucketUpstreamDeletePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BucketUpstreamDeletePayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishBucketUpstreamDeletePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsBucketUpstreamDeletePayload(buf []byte, offset flatbuffers.UOffsetT) *BucketUpstreamDeletePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BucketUpstreamDeletePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedBucketUpstreamDeletePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *BucketUpstreamDeletePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BucketUpstreamDeletePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BucketUpstreamDeletePayload) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func BucketUpstreamDeletePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func BucketUpstreamDeletePayloadAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func BucketUpstreamDeletePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
