// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package iampb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GrantPutPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsGrantPutPayload(buf []byte, offset flatbuffers.UOffsetT) *GrantPutPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GrantPutPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishGrantPutPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGrantPutPayload(buf []byte, offset flatbuffers.UOffsetT) *GrantPutPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GrantPutPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGrantPutPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GrantPutPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GrantPutPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GrantPutPayload) SaId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GrantPutPayload) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GrantPutPayload) Role() Role {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return Role(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *GrantPutPayload) MutateRole(n Role) bool {
	return rcv._tab.MutateByteSlot(8, byte(n))
}

func (rcv *GrantPutPayload) CreatedAtUnixNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GrantPutPayload) MutateCreatedAtUnixNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *GrantPutPayload) CreatedBy() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GrantPutPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func GrantPutPayloadAddSaId(builder *flatbuffers.Builder, saId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(saId), 0)
}
func GrantPutPayloadAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(bucket), 0)
}
func GrantPutPayloadAddRole(builder *flatbuffers.Builder, role Role) {
	builder.PrependByteSlot(2, byte(role), 0)
}
func GrantPutPayloadAddCreatedAtUnixNs(builder *flatbuffers.Builder, createdAtUnixNs int64) {
	builder.PrependInt64Slot(3, createdAtUnixNs, 0)
}
func GrantPutPayloadAddCreatedBy(builder *flatbuffers.Builder, createdBy flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(createdBy), 0)
}
func GrantPutPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
