// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package iampb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GrantWildcardDeletePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsGrantWildcardDeletePayload(buf []byte, offset flatbuffers.UOffsetT) *GrantWildcardDeletePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GrantWildcardDeletePayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishGrantWildcardDeletePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGrantWildcardDeletePayload(buf []byte, offset flatbuffers.UOffsetT) *GrantWildcardDeletePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GrantWildcardDeletePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGrantWildcardDeletePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GrantWildcardDeletePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GrantWildcardDeletePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GrantWildcardDeletePayload) SaId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GrantWildcardDeletePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GrantWildcardDeletePayloadAddSaId(builder *flatbuffers.Builder, saId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(saId), 0)
}
func GrantWildcardDeletePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
