// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package iampb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InitFirstSAPayload struct {
	_tab flatbuffers.Table
}

func GetRootAsInitFirstSAPayload(buf []byte, offset flatbuffers.UOffsetT) *InitFirstSAPayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InitFirstSAPayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishInitFirstSAPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInitFirstSAPayload(buf []byte, offset flatbuffers.UOffsetT) *InitFirstSAPayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InitFirstSAPayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInitFirstSAPayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InitFirstSAPayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InitFirstSAPayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InitFirstSAPayload) SaCreateBlob(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *InitFirstSAPayload) SaCreateBlobLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *InitFirstSAPayload) SaCreateBlobBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InitFirstSAPayload) MutateSaCreateBlob(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *InitFirstSAPayload) KeyCreateBlob(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *InitFirstSAPayload) KeyCreateBlobLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *InitFirstSAPayload) KeyCreateBlobBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InitFirstSAPayload) MutateKeyCreateBlob(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *InitFirstSAPayload) GrantWildcardBlob(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *InitFirstSAPayload) GrantWildcardBlobLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *InitFirstSAPayload) GrantWildcardBlobBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InitFirstSAPayload) MutateGrantWildcardBlob(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func InitFirstSAPayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func InitFirstSAPayloadAddSaCreateBlob(builder *flatbuffers.Builder, saCreateBlob flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(saCreateBlob), 0)
}
func InitFirstSAPayloadStartSaCreateBlobVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func InitFirstSAPayloadAddKeyCreateBlob(builder *flatbuffers.Builder, keyCreateBlob flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(keyCreateBlob), 0)
}
func InitFirstSAPayloadStartKeyCreateBlobVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func InitFirstSAPayloadAddGrantWildcardBlob(builder *flatbuffers.Builder, grantWildcardBlob flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(grantWildcardBlob), 0)
}
func InitFirstSAPayloadStartGrantWildcardBlobVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func InitFirstSAPayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
