// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package iampb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyCreatePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyCreatePayload(buf []byte, offset flatbuffers.UOffsetT) *KeyCreatePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyCreatePayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyCreatePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyCreatePayload(buf []byte, offset flatbuffers.UOffsetT) *KeyCreatePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyCreatePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyCreatePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyCreatePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyCreatePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyCreatePayload) AccessKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyCreatePayload) SecretKeyEnc(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *KeyCreatePayload) SecretKeyEncLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *KeyCreatePayload) SecretKeyEncBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyCreatePayload) MutateSecretKeyEnc(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *KeyCreatePayload) SaId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *KeyCreatePayload) CreatedAtUnixNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KeyCreatePayload) MutateCreatedAtUnixNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(10, n)
}

func (rcv *KeyCreatePayload) ExpiresAtUnixNs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *KeyCreatePayload) MutateExpiresAtUnixNs(n int64) bool {
	return rcv._tab.MutateInt64Slot(12, n)
}

func (rcv *KeyCreatePayload) BucketScope(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *KeyCreatePayload) BucketScopeLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func KeyCreatePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func KeyCreatePayloadAddAccessKey(builder *flatbuffers.Builder, accessKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(accessKey), 0)
}
func KeyCreatePayloadAddSecretKeyEnc(builder *flatbuffers.Builder, secretKeyEnc flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(secretKeyEnc), 0)
}
func KeyCreatePayloadStartSecretKeyEncVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func KeyCreatePayloadAddSaId(builder *flatbuffers.Builder, saId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(saId), 0)
}
func KeyCreatePayloadAddCreatedAtUnixNs(builder *flatbuffers.Builder, createdAtUnixNs int64) {
	builder.PrependInt64Slot(3, createdAtUnixNs, 0)
}
func KeyCreatePayloadAddExpiresAtUnixNs(builder *flatbuffers.Builder, expiresAtUnixNs int64) {
	builder.PrependInt64Slot(4, expiresAtUnixNs, 0)
}
func KeyCreatePayloadAddBucketScope(builder *flatbuffers.Builder, bucketScope flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(bucketScope), 0)
}
func KeyCreatePayloadStartBucketScopeVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func KeyCreatePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
