// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package iampb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type KeyRevokePayload struct {
	_tab flatbuffers.Table
}

func GetRootAsKeyRevokePayload(buf []byte, offset flatbuffers.UOffsetT) *KeyRevokePayload {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &KeyRevokePayload{}
	x.Init(buf, n+offset)
	return x
}

func FinishKeyRevokePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsKeyRevokePayload(buf []byte, offset flatbuffers.UOffsetT) *KeyRevokePayload {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &KeyRevokePayload{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedKeyRevokePayloadBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *KeyRevokePayload) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *KeyRevokePayload) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *KeyRevokePayload) AccessKey() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func KeyRevokePayloadStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func KeyRevokePayloadAddAccessKey(builder *flatbuffers.Builder, accessKey flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(accessKey), 0)
}
func KeyRevokePayloadEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
