// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package iampb

import "strconv"

type KeyStatus byte

const (
	KeyStatusActive  KeyStatus = 1
	KeyStatusRevoked KeyStatus = 2
)

var EnumNamesKeyStatus = map[KeyStatus]string{
	KeyStatusActive:  "Active",
	KeyStatusRevoked: "Revoked",
}

var EnumValuesKeyStatus = map[string]KeyStatus{
	"Active":  KeyStatusActive,
	"Revoked": KeyStatusRevoked,
}

func (v KeyStatus) String() string {
	if s, ok := EnumNamesKeyStatus[v]; ok {
		return s
	}
	return "KeyStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
