// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package iampb

import "strconv"

type Role byte

const (
	RoleNone  Role = 0
	RoleRead  Role = 1
	RoleWrite Role = 2
	RoleAdmin Role = 3
)

var EnumNamesRole = map[Role]string{
	RoleNone:  "None",
	RoleRead:  "Read",
	RoleWrite: "Write",
	RoleAdmin: "Admin",
}

var EnumValuesRole = map[string]Role{
	"None":  RoleNone,
	"Read":  RoleRead,
	"Write": RoleWrite,
	"Admin": RoleAdmin,
}

func (v Role) String() string {
	if s, ok := EnumNamesRole[v]; ok {
		return s
	}
	return "Role(" + strconv.FormatInt(int64(v), 10) + ")"
}
