// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AbortMultipartUploadArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsAbortMultipartUploadArgs(buf []byte, offset flatbuffers.UOffsetT) *AbortMultipartUploadArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AbortMultipartUploadArgs{}
	x.Init(buf, n+offset)
	return x
}

func FinishAbortMultipartUploadArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAbortMultipartUploadArgs(buf []byte, offset flatbuffers.UOffsetT) *AbortMultipartUploadArgs {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AbortMultipartUploadArgs{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAbortMultipartUploadArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AbortMultipartUploadArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AbortMultipartUploadArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AbortMultipartUploadArgs) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AbortMultipartUploadArgs) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AbortMultipartUploadArgs) UploadId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AbortMultipartUploadArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func AbortMultipartUploadArgsAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func AbortMultipartUploadArgsAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func AbortMultipartUploadArgsAddUploadId(builder *flatbuffers.Builder, uploadId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(uploadId), 0)
}
func AbortMultipartUploadArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
