// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AppendEntriesArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsAppendEntriesArgs(buf []byte, offset flatbuffers.UOffsetT) *AppendEntriesArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AppendEntriesArgs{}
	x.Init(buf, n+offset)
	return x
}

func FinishAppendEntriesArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAppendEntriesArgs(buf []byte, offset flatbuffers.UOffsetT) *AppendEntriesArgs {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AppendEntriesArgs{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAppendEntriesArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AppendEntriesArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AppendEntriesArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AppendEntriesArgs) Term() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendEntriesArgs) MutateTerm(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *AppendEntriesArgs) LeaderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AppendEntriesArgs) PrevLogIndex() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendEntriesArgs) MutatePrevLogIndex(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *AppendEntriesArgs) PrevLogTerm() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendEntriesArgs) MutatePrevLogTerm(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *AppendEntriesArgs) Entries(obj *LogEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AppendEntriesArgs) EntriesLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *AppendEntriesArgs) LeaderCommit() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendEntriesArgs) MutateLeaderCommit(n uint64) bool {
	return rcv._tab.MutateUint64Slot(14, n)
}

func AppendEntriesArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func AppendEntriesArgsAddTerm(builder *flatbuffers.Builder, term uint64) {
	builder.PrependUint64Slot(0, term, 0)
}
func AppendEntriesArgsAddLeaderId(builder *flatbuffers.Builder, leaderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(leaderId), 0)
}
func AppendEntriesArgsAddPrevLogIndex(builder *flatbuffers.Builder, prevLogIndex uint64) {
	builder.PrependUint64Slot(2, prevLogIndex, 0)
}
func AppendEntriesArgsAddPrevLogTerm(builder *flatbuffers.Builder, prevLogTerm uint64) {
	builder.PrependUint64Slot(3, prevLogTerm, 0)
}
func AppendEntriesArgsAddEntries(builder *flatbuffers.Builder, entries flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(entries), 0)
}
func AppendEntriesArgsStartEntriesVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AppendEntriesArgsAddLeaderCommit(builder *flatbuffers.Builder, leaderCommit uint64) {
	builder.PrependUint64Slot(5, leaderCommit, 0)
}
func AppendEntriesArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
