// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AppendEntriesReply struct {
	_tab flatbuffers.Table
}

func GetRootAsAppendEntriesReply(buf []byte, offset flatbuffers.UOffsetT) *AppendEntriesReply {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AppendEntriesReply{}
	x.Init(buf, n+offset)
	return x
}

func FinishAppendEntriesReplyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsAppendEntriesReply(buf []byte, offset flatbuffers.UOffsetT) *AppendEntriesReply {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AppendEntriesReply{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedAppendEntriesReplyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *AppendEntriesReply) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AppendEntriesReply) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AppendEntriesReply) Term() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendEntriesReply) MutateTerm(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *AppendEntriesReply) Success() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *AppendEntriesReply) MutateSuccess(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *AppendEntriesReply) ConflictTerm() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendEntriesReply) MutateConflictTerm(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *AppendEntriesReply) ConflictIndex() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *AppendEntriesReply) MutateConflictIndex(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func AppendEntriesReplyStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func AppendEntriesReplyAddTerm(builder *flatbuffers.Builder, term uint64) {
	builder.PrependUint64Slot(0, term, 0)
}
func AppendEntriesReplyAddSuccess(builder *flatbuffers.Builder, success bool) {
	builder.PrependBoolSlot(1, success, false)
}
func AppendEntriesReplyAddConflictTerm(builder *flatbuffers.Builder, conflictTerm uint64) {
	builder.PrependUint64Slot(2, conflictTerm, 0)
}
func AppendEntriesReplyAddConflictIndex(builder *flatbuffers.Builder, conflictIndex uint64) {
	builder.PrependUint64Slot(3, conflictIndex, 0)
}
func AppendEntriesReplyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
