// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ConfChangeEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsConfChangeEntry(buf []byte, offset flatbuffers.UOffsetT) *ConfChangeEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ConfChangeEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishConfChangeEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsConfChangeEntry(buf []byte, offset flatbuffers.UOffsetT) *ConfChangeEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ConfChangeEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedConfChangeEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ConfChangeEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ConfChangeEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ConfChangeEntry) Op() ConfChangeOp {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ConfChangeOp(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ConfChangeEntry) MutateOp(n ConfChangeOp) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *ConfChangeEntry) ServerId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConfChangeEntry) ServerAddress() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ConfChangeEntry) ManagedByJoint() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ConfChangeEntry) MutateManagedByJoint(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func ConfChangeEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func ConfChangeEntryAddOp(builder *flatbuffers.Builder, op ConfChangeOp) {
	builder.PrependInt8Slot(0, int8(op), 0)
}
func ConfChangeEntryAddServerId(builder *flatbuffers.Builder, serverId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(serverId), 0)
}
func ConfChangeEntryAddServerAddress(builder *flatbuffers.Builder, serverAddress flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(serverAddress), 0)
}
func ConfChangeEntryAddManagedByJoint(builder *flatbuffers.Builder, managedByJoint bool) {
	builder.PrependBoolSlot(3, managedByJoint, false)
}
func ConfChangeEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
