// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import "strconv"

type ConfChangeOp int8

const (
	ConfChangeOpAddVoter       ConfChangeOp = 0
	ConfChangeOpRemoveVoter    ConfChangeOp = 1
	ConfChangeOpAddLearner     ConfChangeOp = 2
	ConfChangeOpPromoteToVoter ConfChangeOp = 3
)

var EnumNamesConfChangeOp = map[ConfChangeOp]string{
	ConfChangeOpAddVoter:       "AddVoter",
	ConfChangeOpRemoveVoter:    "RemoveVoter",
	ConfChangeOpAddLearner:     "AddLearner",
	ConfChangeOpPromoteToVoter: "PromoteToVoter",
}

var EnumValuesConfChangeOp = map[string]ConfChangeOp{
	"AddVoter":       ConfChangeOpAddVoter,
	"RemoveVoter":    ConfChangeOpRemoveVoter,
	"AddLearner":     ConfChangeOpAddLearner,
	"PromoteToVoter": ConfChangeOpPromoteToVoter,
}

func (v ConfChangeOp) String() string {
	if s, ok := EnumNamesConfChangeOp[v]; ok {
		return s
	}
	return "ConfChangeOp(" + strconv.FormatInt(int64(v), 10) + ")"
}
