// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DeleteObjectVersionArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteObjectVersionArgs(buf []byte, offset flatbuffers.UOffsetT) *DeleteObjectVersionArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteObjectVersionArgs{}
	x.Init(buf, n+offset)
	return x
}

func FinishDeleteObjectVersionArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsDeleteObjectVersionArgs(buf []byte, offset flatbuffers.UOffsetT) *DeleteObjectVersionArgs {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeleteObjectVersionArgs{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedDeleteObjectVersionArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *DeleteObjectVersionArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteObjectVersionArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteObjectVersionArgs) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeleteObjectVersionArgs) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DeleteObjectVersionArgs) VersionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DeleteObjectVersionArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func DeleteObjectVersionArgsAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func DeleteObjectVersionArgsAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func DeleteObjectVersionArgsAddVersionId(builder *flatbuffers.Builder, versionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(versionId), 0)
}
func DeleteObjectVersionArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
