// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ForwardMultipartUploadMeta struct {
	_tab flatbuffers.Table
}

func GetRootAsForwardMultipartUploadMeta(buf []byte, offset flatbuffers.UOffsetT) *ForwardMultipartUploadMeta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ForwardMultipartUploadMeta{}
	x.Init(buf, n+offset)
	return x
}

func FinishForwardMultipartUploadMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsForwardMultipartUploadMeta(buf []byte, offset flatbuffers.UOffsetT) *ForwardMultipartUploadMeta {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ForwardMultipartUploadMeta{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedForwardMultipartUploadMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ForwardMultipartUploadMeta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ForwardMultipartUploadMeta) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ForwardMultipartUploadMeta) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ForwardMultipartUploadMeta) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ForwardMultipartUploadMeta) UploadId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ForwardMultipartUploadMetaStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ForwardMultipartUploadMetaAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func ForwardMultipartUploadMetaAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func ForwardMultipartUploadMetaAddUploadId(builder *flatbuffers.Builder, uploadId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(uploadId), 0)
}
func ForwardMultipartUploadMetaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
