// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import "strconv"

type ForwardStatus int8

const (
	ForwardStatusOK                           ForwardStatus = 0
	ForwardStatusNotLeader                    ForwardStatus = 1
	ForwardStatusNotVoter                     ForwardStatus = 2
	ForwardStatusNoSuchBucket                 ForwardStatus = 3
	ForwardStatusNoSuchKey                    ForwardStatus = 4
	ForwardStatusEntityTooLarge               ForwardStatus = 5
	ForwardStatusInsufficientPlacementTargets ForwardStatus = 6
	ForwardStatusNoSuchUpload                 ForwardStatus = 7
	ForwardStatusAppendOffsetMismatch         ForwardStatus = 8
	ForwardStatusAppendNotSupported           ForwardStatus = 9
	ForwardStatusAppendCapExceeded            ForwardStatus = 10
	ForwardStatusAppendObjectTooLarge         ForwardStatus = 11
	ForwardStatusMethodNotAllowed             ForwardStatus = 12
	ForwardStatusInternal                     ForwardStatus = 99
)

var EnumNamesForwardStatus = map[ForwardStatus]string{
	ForwardStatusOK:                           "OK",
	ForwardStatusNotLeader:                    "NotLeader",
	ForwardStatusNotVoter:                     "NotVoter",
	ForwardStatusNoSuchBucket:                 "NoSuchBucket",
	ForwardStatusNoSuchKey:                    "NoSuchKey",
	ForwardStatusEntityTooLarge:               "EntityTooLarge",
	ForwardStatusInsufficientPlacementTargets: "InsufficientPlacementTargets",
	ForwardStatusNoSuchUpload:                 "NoSuchUpload",
	ForwardStatusAppendOffsetMismatch:         "AppendOffsetMismatch",
	ForwardStatusAppendNotSupported:           "AppendNotSupported",
	ForwardStatusAppendCapExceeded:            "AppendCapExceeded",
	ForwardStatusAppendObjectTooLarge:         "AppendObjectTooLarge",
	ForwardStatusMethodNotAllowed:             "MethodNotAllowed",
	ForwardStatusInternal:                     "Internal",
}

var EnumValuesForwardStatus = map[string]ForwardStatus{
	"OK":                           ForwardStatusOK,
	"NotLeader":                    ForwardStatusNotLeader,
	"NotVoter":                     ForwardStatusNotVoter,
	"NoSuchBucket":                 ForwardStatusNoSuchBucket,
	"NoSuchKey":                    ForwardStatusNoSuchKey,
	"EntityTooLarge":               ForwardStatusEntityTooLarge,
	"InsufficientPlacementTargets": ForwardStatusInsufficientPlacementTargets,
	"NoSuchUpload":                 ForwardStatusNoSuchUpload,
	"AppendOffsetMismatch":         ForwardStatusAppendOffsetMismatch,
	"AppendNotSupported":           ForwardStatusAppendNotSupported,
	"AppendCapExceeded":            ForwardStatusAppendCapExceeded,
	"AppendObjectTooLarge":         ForwardStatusAppendObjectTooLarge,
	"MethodNotAllowed":             ForwardStatusMethodNotAllowed,
	"Internal":                     ForwardStatusInternal,
}

func (v ForwardStatus) String() string {
	if s, ok := EnumNamesForwardStatus[v]; ok {
		return s
	}
	return "ForwardStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
