// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import "strconv"

type ForwardStatus int8

const (
	ForwardStatusOK             ForwardStatus = 0
	ForwardStatusNotLeader      ForwardStatus = 1
	ForwardStatusNotVoter       ForwardStatus = 2
	ForwardStatusNoSuchBucket   ForwardStatus = 3
	ForwardStatusNoSuchKey      ForwardStatus = 4
	ForwardStatusEntityTooLarge ForwardStatus = 5
	ForwardStatusInternal       ForwardStatus = 99
)

var EnumNamesForwardStatus = map[ForwardStatus]string{
	ForwardStatusOK:             "OK",
	ForwardStatusNotLeader:      "NotLeader",
	ForwardStatusNotVoter:       "NotVoter",
	ForwardStatusNoSuchBucket:   "NoSuchBucket",
	ForwardStatusNoSuchKey:      "NoSuchKey",
	ForwardStatusEntityTooLarge: "EntityTooLarge",
	ForwardStatusInternal:       "Internal",
}

var EnumValuesForwardStatus = map[string]ForwardStatus{
	"OK":             ForwardStatusOK,
	"NotLeader":      ForwardStatusNotLeader,
	"NotVoter":       ForwardStatusNotVoter,
	"NoSuchBucket":   ForwardStatusNoSuchBucket,
	"NoSuchKey":      ForwardStatusNoSuchKey,
	"EntityTooLarge": ForwardStatusEntityTooLarge,
	"Internal":       ForwardStatusInternal,
}

func (v ForwardStatus) String() string {
	if s, ok := EnumNamesForwardStatus[v]; ok {
		return s
	}
	return "ForwardStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
