// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ForwardObjectMeta struct {
	_tab flatbuffers.Table
}

func GetRootAsForwardObjectMeta(buf []byte, offset flatbuffers.UOffsetT) *ForwardObjectMeta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ForwardObjectMeta{}
	x.Init(buf, n+offset)
	return x
}

func FinishForwardObjectMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsForwardObjectMeta(buf []byte, offset flatbuffers.UOffsetT) *ForwardObjectMeta {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ForwardObjectMeta{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedForwardObjectMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ForwardObjectMeta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ForwardObjectMeta) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ForwardObjectMeta) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ForwardObjectMeta) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ForwardObjectMeta) Size() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ForwardObjectMeta) MutateSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(8, n)
}

func (rcv *ForwardObjectMeta) Etag() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ForwardObjectMeta) ContentType() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ForwardObjectMeta) ModifiedUnixMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ForwardObjectMeta) MutateModifiedUnixMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(14, n)
}

func (rcv *ForwardObjectMeta) VersionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ForwardObjectMetaStart(builder *flatbuffers.Builder) {
	builder.StartObject(7)
}
func ForwardObjectMetaAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func ForwardObjectMetaAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func ForwardObjectMetaAddSize(builder *flatbuffers.Builder, size int64) {
	builder.PrependInt64Slot(2, size, 0)
}
func ForwardObjectMetaAddEtag(builder *flatbuffers.Builder, etag flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(etag), 0)
}
func ForwardObjectMetaAddContentType(builder *flatbuffers.Builder, contentType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(contentType), 0)
}
func ForwardObjectMetaAddModifiedUnixMs(builder *flatbuffers.Builder, modifiedUnixMs int64) {
	builder.PrependInt64Slot(5, modifiedUnixMs, 0)
}
func ForwardObjectMetaAddVersionId(builder *flatbuffers.Builder, versionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(versionId), 0)
}
func ForwardObjectMetaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
