// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetObjectVersionArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsGetObjectVersionArgs(buf []byte, offset flatbuffers.UOffsetT) *GetObjectVersionArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetObjectVersionArgs{}
	x.Init(buf, n+offset)
	return x
}

func FinishGetObjectVersionArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGetObjectVersionArgs(buf []byte, offset flatbuffers.UOffsetT) *GetObjectVersionArgs {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GetObjectVersionArgs{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGetObjectVersionArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GetObjectVersionArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetObjectVersionArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetObjectVersionArgs) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GetObjectVersionArgs) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GetObjectVersionArgs) VersionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GetObjectVersionArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GetObjectVersionArgsAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func GetObjectVersionArgsAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func GetObjectVersionArgsAddVersionId(builder *flatbuffers.Builder, versionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(versionId), 0)
}
func GetObjectVersionArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
