// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type InstallSnapshotArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsInstallSnapshotArgs(buf []byte, offset flatbuffers.UOffsetT) *InstallSnapshotArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &InstallSnapshotArgs{}
	x.Init(buf, n+offset)
	return x
}

func FinishInstallSnapshotArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsInstallSnapshotArgs(buf []byte, offset flatbuffers.UOffsetT) *InstallSnapshotArgs {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &InstallSnapshotArgs{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedInstallSnapshotArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *InstallSnapshotArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *InstallSnapshotArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *InstallSnapshotArgs) Term() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InstallSnapshotArgs) MutateTerm(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *InstallSnapshotArgs) LeaderId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InstallSnapshotArgs) LastIncludedIndex() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InstallSnapshotArgs) MutateLastIncludedIndex(n uint64) bool {
	return rcv._tab.MutateUint64Slot(8, n)
}

func (rcv *InstallSnapshotArgs) LastIncludedTerm() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *InstallSnapshotArgs) MutateLastIncludedTerm(n uint64) bool {
	return rcv._tab.MutateUint64Slot(10, n)
}

func (rcv *InstallSnapshotArgs) Data(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *InstallSnapshotArgs) DataLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *InstallSnapshotArgs) DataBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *InstallSnapshotArgs) MutateData(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func InstallSnapshotArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func InstallSnapshotArgsAddTerm(builder *flatbuffers.Builder, term uint64) {
	builder.PrependUint64Slot(0, term, 0)
}
func InstallSnapshotArgsAddLeaderId(builder *flatbuffers.Builder, leaderId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(leaderId), 0)
}
func InstallSnapshotArgsAddLastIncludedIndex(builder *flatbuffers.Builder, lastIncludedIndex uint64) {
	builder.PrependUint64Slot(2, lastIncludedIndex, 0)
}
func InstallSnapshotArgsAddLastIncludedTerm(builder *flatbuffers.Builder, lastIncludedTerm uint64) {
	builder.PrependUint64Slot(3, lastIncludedTerm, 0)
}
func InstallSnapshotArgsAddData(builder *flatbuffers.Builder, data flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(data), 0)
}
func InstallSnapshotArgsStartDataVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func InstallSnapshotArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
