// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type JointConfChangeEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsJointConfChangeEntry(buf []byte, offset flatbuffers.UOffsetT) *JointConfChangeEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JointConfChangeEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishJointConfChangeEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsJointConfChangeEntry(buf []byte, offset flatbuffers.UOffsetT) *JointConfChangeEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JointConfChangeEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedJointConfChangeEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *JointConfChangeEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JointConfChangeEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JointConfChangeEntry) Op() JointOp {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return JointOp(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *JointConfChangeEntry) MutateOp(n JointOp) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *JointConfChangeEntry) NewServers(obj *ServerEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *JointConfChangeEntry) NewServersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *JointConfChangeEntry) OldServers(obj *ServerEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *JointConfChangeEntry) OldServersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func JointConfChangeEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func JointConfChangeEntryAddOp(builder *flatbuffers.Builder, op JointOp) {
	builder.PrependInt8Slot(0, int8(op), 0)
}
func JointConfChangeEntryAddNewServers(builder *flatbuffers.Builder, newServers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(newServers), 0)
}
func JointConfChangeEntryStartNewServersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func JointConfChangeEntryAddOldServers(builder *flatbuffers.Builder, oldServers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(oldServers), 0)
}
func JointConfChangeEntryStartOldServersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func JointConfChangeEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
