// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListObjectsArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsListObjectsArgs(buf []byte, offset flatbuffers.UOffsetT) *ListObjectsArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListObjectsArgs{}
	x.Init(buf, n+offset)
	return x
}

func FinishListObjectsArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsListObjectsArgs(buf []byte, offset flatbuffers.UOffsetT) *ListObjectsArgs {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListObjectsArgs{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedListObjectsArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ListObjectsArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListObjectsArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListObjectsArgs) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ListObjectsArgs) Prefix() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ListObjectsArgs) MaxKeys() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ListObjectsArgs) MutateMaxKeys(n int32) bool {
	return rcv._tab.MutateInt32Slot(8, n)
}

func ListObjectsArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func ListObjectsArgsAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func ListObjectsArgsAddPrefix(builder *flatbuffers.Builder, prefix flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(prefix), 0)
}
func ListObjectsArgsAddMaxKeys(builder *flatbuffers.Builder, maxKeys int32) {
	builder.PrependInt32Slot(2, maxKeys, 0)
}
func ListObjectsArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
