// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ListPartsArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsListPartsArgs(buf []byte, offset flatbuffers.UOffsetT) *ListPartsArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ListPartsArgs{}
	x.Init(buf, n+offset)
	return x
}

func FinishListPartsArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsListPartsArgs(buf []byte, offset flatbuffers.UOffsetT) *ListPartsArgs {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ListPartsArgs{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedListPartsArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ListPartsArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ListPartsArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ListPartsArgs) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ListPartsArgs) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ListPartsArgs) UploadId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ListPartsArgs) MaxParts() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ListPartsArgs) MutateMaxParts(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func ListPartsArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ListPartsArgsAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func ListPartsArgsAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(key), 0)
}
func ListPartsArgsAddUploadId(builder *flatbuffers.Builder, uploadId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(uploadId), 0)
}
func ListPartsArgsAddMaxParts(builder *flatbuffers.Builder, maxParts int32) {
	builder.PrependInt32Slot(3, maxParts, 0)
}
func ListPartsArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
