// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import "strconv"

type LogEntryType int8

const (
	LogEntryTypeCommand         LogEntryType = 0
	LogEntryTypeConfChange      LogEntryType = 1
	LogEntryTypeJointConfChange LogEntryType = 2
)

var EnumNamesLogEntryType = map[LogEntryType]string{
	LogEntryTypeCommand:         "Command",
	LogEntryTypeConfChange:      "ConfChange",
	LogEntryTypeJointConfChange: "JointConfChange",
}

var EnumValuesLogEntryType = map[string]LogEntryType{
	"Command":         LogEntryTypeCommand,
	"ConfChange":      LogEntryTypeConfChange,
	"JointConfChange": LogEntryTypeJointConfChange,
}

func (v LogEntryType) String() string {
	if s, ok := EnumNamesLogEntryType[v]; ok {
		return s
	}
	return "LogEntryType(" + strconv.FormatInt(int64(v), 10) + ")"
}
