// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ScrubSessionStatReply struct {
	_tab flatbuffers.Table
}

func GetRootAsScrubSessionStatReply(buf []byte, offset flatbuffers.UOffsetT) *ScrubSessionStatReply {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ScrubSessionStatReply{}
	x.Init(buf, n+offset)
	return x
}

func FinishScrubSessionStatReplyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsScrubSessionStatReply(buf []byte, offset flatbuffers.UOffsetT) *ScrubSessionStatReply {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ScrubSessionStatReply{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedScrubSessionStatReplyBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ScrubSessionStatReply) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ScrubSessionStatReply) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ScrubSessionStatReply) Found() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ScrubSessionStatReply) MutateFound(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *ScrubSessionStatReply) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScrubSessionStatReply) KeyPrefix() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScrubSessionStatReply) Scope() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrubSessionStatReply) MutateScope(n int32) bool {
	return rcv._tab.MutateInt32Slot(10, n)
}

func (rcv *ScrubSessionStatReply) DryRun() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ScrubSessionStatReply) MutateDryRun(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *ScrubSessionStatReply) Status() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ScrubSessionStatReply) StartedAt() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrubSessionStatReply) MutateStartedAt(n int64) bool {
	return rcv._tab.MutateInt64Slot(16, n)
}

func (rcv *ScrubSessionStatReply) DoneAt() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrubSessionStatReply) MutateDoneAt(n int64) bool {
	return rcv._tab.MutateInt64Slot(18, n)
}

func (rcv *ScrubSessionStatReply) Checked() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrubSessionStatReply) MutateChecked(n int64) bool {
	return rcv._tab.MutateInt64Slot(20, n)
}

func (rcv *ScrubSessionStatReply) Healthy() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrubSessionStatReply) MutateHealthy(n int64) bool {
	return rcv._tab.MutateInt64Slot(22, n)
}

func (rcv *ScrubSessionStatReply) Detected() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrubSessionStatReply) MutateDetected(n int64) bool {
	return rcv._tab.MutateInt64Slot(24, n)
}

func (rcv *ScrubSessionStatReply) Repaired() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrubSessionStatReply) MutateRepaired(n int64) bool {
	return rcv._tab.MutateInt64Slot(26, n)
}

func (rcv *ScrubSessionStatReply) Unrepairable() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrubSessionStatReply) MutateUnrepairable(n int64) bool {
	return rcv._tab.MutateInt64Slot(28, n)
}

func (rcv *ScrubSessionStatReply) Skipped() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(30))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ScrubSessionStatReply) MutateSkipped(n int64) bool {
	return rcv._tab.MutateInt64Slot(30, n)
}

func (rcv *ScrubSessionStatReply) OwnedHere() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(32))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *ScrubSessionStatReply) MutateOwnedHere(n bool) bool {
	return rcv._tab.MutateBoolSlot(32, n)
}

func ScrubSessionStatReplyStart(builder *flatbuffers.Builder) {
	builder.StartObject(15)
}
func ScrubSessionStatReplyAddFound(builder *flatbuffers.Builder, found bool) {
	builder.PrependBoolSlot(0, found, false)
}
func ScrubSessionStatReplyAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(bucket), 0)
}
func ScrubSessionStatReplyAddKeyPrefix(builder *flatbuffers.Builder, keyPrefix flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(keyPrefix), 0)
}
func ScrubSessionStatReplyAddScope(builder *flatbuffers.Builder, scope int32) {
	builder.PrependInt32Slot(3, scope, 0)
}
func ScrubSessionStatReplyAddDryRun(builder *flatbuffers.Builder, dryRun bool) {
	builder.PrependBoolSlot(4, dryRun, false)
}
func ScrubSessionStatReplyAddStatus(builder *flatbuffers.Builder, status flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(status), 0)
}
func ScrubSessionStatReplyAddStartedAt(builder *flatbuffers.Builder, startedAt int64) {
	builder.PrependInt64Slot(6, startedAt, 0)
}
func ScrubSessionStatReplyAddDoneAt(builder *flatbuffers.Builder, doneAt int64) {
	builder.PrependInt64Slot(7, doneAt, 0)
}
func ScrubSessionStatReplyAddChecked(builder *flatbuffers.Builder, checked int64) {
	builder.PrependInt64Slot(8, checked, 0)
}
func ScrubSessionStatReplyAddHealthy(builder *flatbuffers.Builder, healthy int64) {
	builder.PrependInt64Slot(9, healthy, 0)
}
func ScrubSessionStatReplyAddDetected(builder *flatbuffers.Builder, detected int64) {
	builder.PrependInt64Slot(10, detected, 0)
}
func ScrubSessionStatReplyAddRepaired(builder *flatbuffers.Builder, repaired int64) {
	builder.PrependInt64Slot(11, repaired, 0)
}
func ScrubSessionStatReplyAddUnrepairable(builder *flatbuffers.Builder, unrepairable int64) {
	builder.PrependInt64Slot(12, unrepairable, 0)
}
func ScrubSessionStatReplyAddSkipped(builder *flatbuffers.Builder, skipped int64) {
	builder.PrependInt64Slot(13, skipped, 0)
}
func ScrubSessionStatReplyAddOwnedHere(builder *flatbuffers.Builder, ownedHere bool) {
	builder.PrependBoolSlot(14, ownedHere, false)
}
func ScrubSessionStatReplyEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
