// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SnapshotMeta struct {
	_tab flatbuffers.Table
}

func GetRootAsSnapshotMeta(buf []byte, offset flatbuffers.UOffsetT) *SnapshotMeta {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SnapshotMeta{}
	x.Init(buf, n+offset)
	return x
}

func FinishSnapshotMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSnapshotMeta(buf []byte, offset flatbuffers.UOffsetT) *SnapshotMeta {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SnapshotMeta{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSnapshotMetaBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SnapshotMeta) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SnapshotMeta) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SnapshotMeta) Index() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotMeta) MutateIndex(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *SnapshotMeta) Term() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SnapshotMeta) MutateTerm(n uint64) bool {
	return rcv._tab.MutateUint64Slot(6, n)
}

func (rcv *SnapshotMeta) Servers(obj *ServerEntry, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *SnapshotMeta) ServersLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func SnapshotMetaStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SnapshotMetaAddIndex(builder *flatbuffers.Builder, index uint64) {
	builder.PrependUint64Slot(0, index, 0)
}
func SnapshotMetaAddTerm(builder *flatbuffers.Builder, term uint64) {
	builder.PrependUint64Slot(1, term, 0)
}
func SnapshotMetaAddServers(builder *flatbuffers.Builder, servers flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(servers), 0)
}
func SnapshotMetaStartServersVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func SnapshotMetaEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
