// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package raftpb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type WalkObjectsArgs struct {
	_tab flatbuffers.Table
}

func GetRootAsWalkObjectsArgs(buf []byte, offset flatbuffers.UOffsetT) *WalkObjectsArgs {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &WalkObjectsArgs{}
	x.Init(buf, n+offset)
	return x
}

func FinishWalkObjectsArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsWalkObjectsArgs(buf []byte, offset flatbuffers.UOffsetT) *WalkObjectsArgs {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &WalkObjectsArgs{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedWalkObjectsArgsBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *WalkObjectsArgs) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *WalkObjectsArgs) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *WalkObjectsArgs) Bucket() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *WalkObjectsArgs) Prefix() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func WalkObjectsArgsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func WalkObjectsArgsAddBucket(builder *flatbuffers.Builder, bucket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(bucket), 0)
}
func WalkObjectsArgsAddPrefix(builder *flatbuffers.Builder, prefix flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(prefix), 0)
}
func WalkObjectsArgsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
